// <auto-generated />
using System;
using BADBIR.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BADBIR.Api.Migrations
{
    [DbContext(typeof(BadbirDbContext))]
    partial class BadbirDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BADBIR.Api.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClinicalCentre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClinicianPatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsentVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("DiagnosisConfirmedIA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HoldingExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyInfoComms")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyReminders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RegistrationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("SelfReportedDiagnosis")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.CageSubmission", b =>
                {
                    b.Property<int>("CageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Annoyed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Cutdown")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Earlymorning")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Guilty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CageId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("CageSubmissions", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.ConsentRecord", b =>
                {
                    b.Property<int>("ConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsentFormVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConsentTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("SignatureType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConsentId");

                    b.HasIndex("UserId");

                    b.ToTable("ConsentRecords", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.DlqiSubmission", b =>
                {
                    b.Property<int>("DlqiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClothesScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmbscScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItchsoreScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartcrfScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SexdifScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShophgScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkipBreakup")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SocleisScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SportScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TreatmentScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkstudScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkstudnoScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("DlqiId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("DlqiSubmissions", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.EuroqolSubmission", b =>
                {
                    b.Property<int>("EuroqolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Anxdepr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Comphealth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Howyoufeel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Mobility")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Paindisc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Selfcare")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Usualacts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EuroqolId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("EuroqolSubmissions", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.HadsSubmission", b =>
                {
                    b.Property<int>("HadsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateScored")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCountable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Q01tense")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q02enjoy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q03frightened")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q04laugh")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q05worry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q06cheerful")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q07relaxed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q08slowed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q09butterflies")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q10appearence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q11restless")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q12enjoyment")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q13panic")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q14goodbook")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultAnxiety")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultDepression")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScoreAnxiety")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScoreDepression")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HadsId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("HadsSubmissions", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.HaqSubmission", b =>
                {
                    b.Property<int>("HaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bath")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bathrail")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bathseat")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bend")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cane")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cardoor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Climbsteps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Crutches")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cutmeat")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateScored")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deviceother")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dressgroom")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Dressing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dressingdetails")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dressself")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Eating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Errands")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Getincar")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Gripping")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Haqscore")
                        .HasColumnType("REAL");

                    b.Property<int?>("Housework")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Hygiene")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Jaropener")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Liftglass")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Longreach")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Loolift")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Missingdata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Missingdatadetails")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Openjar")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Openmilk")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Reach")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Reachabove")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rising")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Shampoo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Shop")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Specialchair")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Specialutensils")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Standchair")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Toilet")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Totalscore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Turntap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Walker")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Walkflat")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Walking")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Washdry")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Wheelchair")
                        .HasColumnType("INTEGER");

                    b.HasKey("HaqId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("HaqSubmissions", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.LifestyleSubmission", b =>
                {
                    b.Property<int>("LifestyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Admittedtohospital")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Agestart")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Agestop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthcountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Birthtown")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Currentlysmoke")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Currentlysmokenumbercigsperday")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Diastolic")
                        .HasColumnType("REAL");

                    b.Property<bool?>("Drinkalcohol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DrinkingMissing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Drnkbeeravg")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Drnkspiritsavg")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Drnkunitsavg")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Drnkwineavg")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ethnicityid")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Eversmoked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Eversmokednumbercigsperday")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Height")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Livetropical")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Newclinics")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Newdrugs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Otherethnicity")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Outdooroccupation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmokingMissing")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Systolic")
                        .HasColumnType("REAL");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Waist")
                        .HasColumnType("REAL");

                    b.Property<bool>("WaistMissing")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Weight")
                        .HasColumnType("REAL");

                    b.Property<bool>("WeightMissing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Workstatusid")
                        .HasColumnType("INTEGER");

                    b.HasKey("LifestyleId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("LifestyleSubmissions", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.PgaSubmission", b =>
                {
                    b.Property<int>("PgaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateScored")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Pgascore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PgaId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("PgaSubmissions", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.SapasiSubmission", b =>
                {
                    b.Property<int>("SapasiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateScored")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeadCoverage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadDesquamation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadErythema")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadInduration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LowerLimbsCoverage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LowerLimbsDesquamation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LowerLimbsErythema")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LowerLimbsInduration")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("SapasiScore")
                        .HasColumnType("REAL");

                    b.Property<int?>("TrunkCoverage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrunkDesquamation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrunkErythema")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrunkInduration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpperLimbsCoverage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpperLimbsDesquamation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpperLimbsErythema")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpperLimbsInduration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SapasiId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("SapasiSubmissions", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.VisitTracking", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClinicianPatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportedFupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PotentialFupCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitId");

                    b.HasIndex("UserId");

                    b.ToTable("VisitTracking", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.CageSubmission", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.VisitTracking", "Visit")
                        .WithOne("Cage")
                        .HasForeignKey("BADBIR.Api.Data.Entities.CageSubmission", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.ConsentRecord", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.ApplicationUser", "User")
                        .WithMany("ConsentRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.DlqiSubmission", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.VisitTracking", "Visit")
                        .WithOne("Dlqi")
                        .HasForeignKey("BADBIR.Api.Data.Entities.DlqiSubmission", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.EuroqolSubmission", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.VisitTracking", "Visit")
                        .WithOne("Euroqol")
                        .HasForeignKey("BADBIR.Api.Data.Entities.EuroqolSubmission", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.HadsSubmission", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.VisitTracking", "Visit")
                        .WithOne("Hads")
                        .HasForeignKey("BADBIR.Api.Data.Entities.HadsSubmission", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.HaqSubmission", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.VisitTracking", "Visit")
                        .WithOne("Haq")
                        .HasForeignKey("BADBIR.Api.Data.Entities.HaqSubmission", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.LifestyleSubmission", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.VisitTracking", "Visit")
                        .WithOne("Lifestyle")
                        .HasForeignKey("BADBIR.Api.Data.Entities.LifestyleSubmission", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.PgaSubmission", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.VisitTracking", "Visit")
                        .WithOne("Pga")
                        .HasForeignKey("BADBIR.Api.Data.Entities.PgaSubmission", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.SapasiSubmission", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.VisitTracking", "Visit")
                        .WithOne("Sapasi")
                        .HasForeignKey("BADBIR.Api.Data.Entities.SapasiSubmission", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.VisitTracking", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.ApplicationUser", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BADBIR.Api.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BADBIR.Api.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ConsentRecords");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("BADBIR.Api.Data.Entities.VisitTracking", b =>
                {
                    b.Navigation("Cage");

                    b.Navigation("Dlqi");

                    b.Navigation("Euroqol");

                    b.Navigation("Hads");

                    b.Navigation("Haq");

                    b.Navigation("Lifestyle");

                    b.Navigation("Pga");

                    b.Navigation("Sapasi");
                });
#pragma warning restore 612, 618
        }
    }
}
