
/*
	File generated by NetTiers templates [www.nettiers.net]
	Generated on : 03 July 2020
	Important: Do not modify this file. Edit the file BbCentreRegionlkp.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using MHS.Badbir.NetTiers.Entities.Validation;
#endregion

namespace MHS.Badbir.NetTiers.Entities
{
	///<summary>
	/// Region for centre	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class BbCentreRegionlkpBase : EntityBase, IBbCentreRegionlkp, IEntityId<BbCentreRegionlkpKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private BbCentreRegionlkpEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private BbCentreRegionlkpEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private BbCentreRegionlkpEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<BbCentreRegionlkp> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbCentreRegionlkpEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbCentreRegionlkpEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="BbCentreRegionlkpBase"/> instance.
		///</summary>
		public BbCentreRegionlkpBase()
		{
			this.entityData = new BbCentreRegionlkpEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="BbCentreRegionlkpBase"/> instance.
		///</summary>
		///<param name="_centrereregion">Region</param>
		///<param name="_createdbyid">Created by (id)</param>
		///<param name="_createdbyname">Created by</param>
		///<param name="_createddate">Date created</param>
		///<param name="_lastupdatedbyid">Last updated by (id)</param>
		///<param name="_lastupdatedbyname">Last updated by</param>
		///<param name="_lastupdateddate">Date last updated</param>
		public BbCentreRegionlkpBase(System.String _centrereregion, System.Int32 _createdbyid, 
			System.String _createdbyname, System.DateTime _createddate, System.Int32 _lastupdatedbyid, 
			System.String _lastupdatedbyname, System.DateTime _lastupdateddate)
		{
			this.entityData = new BbCentreRegionlkpEntityData();
			this.backupData = null;

			this.Centrereregion = _centrereregion;
			this.Createdbyid = _createdbyid;
			this.Createdbyname = _createdbyname;
			this.Createddate = _createddate;
			this.Lastupdatedbyid = _lastupdatedbyid;
			this.Lastupdatedbyname = _lastupdatedbyname;
			this.Lastupdateddate = _lastupdateddate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="BbCentreRegionlkp"/> instance.
		///</summary>
		///<param name="_centrereregion">Region</param>
		///<param name="_createdbyid">Created by (id)</param>
		///<param name="_createdbyname">Created by</param>
		///<param name="_createddate">Date created</param>
		///<param name="_lastupdatedbyid">Last updated by (id)</param>
		///<param name="_lastupdatedbyname">Last updated by</param>
		///<param name="_lastupdateddate">Date last updated</param>
		public static BbCentreRegionlkp CreateBbCentreRegionlkp(System.String _centrereregion, System.Int32 _createdbyid, 
			System.String _createdbyname, System.DateTime _createddate, System.Int32 _lastupdatedbyid, 
			System.String _lastupdatedbyname, System.DateTime _lastupdateddate)
		{
			BbCentreRegionlkp newBbCentreRegionlkp = new BbCentreRegionlkp();
			newBbCentreRegionlkp.Centrereregion = _centrereregion;
			newBbCentreRegionlkp.Createdbyid = _createdbyid;
			newBbCentreRegionlkp.Createdbyname = _createdbyname;
			newBbCentreRegionlkp.Createddate = _createddate;
			newBbCentreRegionlkp.Lastupdatedbyid = _lastupdatedbyid;
			newBbCentreRegionlkp.Lastupdatedbyname = _lastupdatedbyname;
			newBbCentreRegionlkp.Lastupdateddate = _lastupdateddate;
			return newBbCentreRegionlkp;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Centreregid property. 
		///		Region Id
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@"Region Id"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 Centreregid
		{
			get
			{
				return this.entityData.Centreregid; 
			}
			
			set
			{
				if (this.entityData.Centreregid == value)
					return;
				
                OnPropertyChanging("Centreregid");                    
				OnColumnChanging(BbCentreRegionlkpColumn.Centreregid, this.entityData.Centreregid);
				this.entityData.Centreregid = value;
				this.EntityId.Centreregid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCentreRegionlkpColumn.Centreregid, this.entityData.Centreregid);
				OnPropertyChanged("Centreregid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Centrereregion property. 
		///		Region
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Region"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Centrereregion
		{
			get
			{
				return this.entityData.Centrereregion; 
			}
			
			set
			{
				if (this.entityData.Centrereregion == value)
					return;
				
                OnPropertyChanging("Centrereregion");                    
				OnColumnChanging(BbCentreRegionlkpColumn.Centrereregion, this.entityData.Centrereregion);
				this.entityData.Centrereregion = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCentreRegionlkpColumn.Centrereregion, this.entityData.Centrereregion);
				OnPropertyChanged("Centrereregion");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyid property. 
		///		Created by (id)
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Created by (id)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Createdbyid
		{
			get
			{
				return this.entityData.Createdbyid; 
			}
			
			set
			{
				if (this.entityData.Createdbyid == value)
					return;
				
                OnPropertyChanging("Createdbyid");                    
				OnColumnChanging(BbCentreRegionlkpColumn.Createdbyid, this.entityData.Createdbyid);
				this.entityData.Createdbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCentreRegionlkpColumn.Createdbyid, this.entityData.Createdbyid);
				OnPropertyChanged("Createdbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyname property. 
		///		Created by
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@"Created by"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual System.String Createdbyname
		{
			get
			{
				return this.entityData.Createdbyname; 
			}
			
			set
			{
				if (this.entityData.Createdbyname == value)
					return;
				
                OnPropertyChanging("Createdbyname");                    
				OnColumnChanging(BbCentreRegionlkpColumn.Createdbyname, this.entityData.Createdbyname);
				this.entityData.Createdbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCentreRegionlkpColumn.Createdbyname, this.entityData.Createdbyname);
				OnPropertyChanged("Createdbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createddate property. 
		///		Date created
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Date created"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Createddate
		{
			get
			{
				return this.entityData.Createddate; 
			}
			
			set
			{
				if (this.entityData.Createddate == value)
					return;
				
                OnPropertyChanging("Createddate");                    
				OnColumnChanging(BbCentreRegionlkpColumn.Createddate, this.entityData.Createddate);
				this.entityData.Createddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCentreRegionlkpColumn.Createddate, this.entityData.Createddate);
				OnPropertyChanged("Createddate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyid property. 
		///		Last updated by (id)
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Last updated by (id)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Lastupdatedbyid
		{
			get
			{
				return this.entityData.Lastupdatedbyid; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyid == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyid");                    
				OnColumnChanging(BbCentreRegionlkpColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				this.entityData.Lastupdatedbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCentreRegionlkpColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				OnPropertyChanged("Lastupdatedbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyname property. 
		///		Last updated by
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@"Last updated by"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual System.String Lastupdatedbyname
		{
			get
			{
				return this.entityData.Lastupdatedbyname; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyname == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyname");                    
				OnColumnChanging(BbCentreRegionlkpColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				this.entityData.Lastupdatedbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCentreRegionlkpColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				OnPropertyChanged("Lastupdatedbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdateddate property. 
		///		Date last updated
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Date last updated"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Lastupdateddate
		{
			get
			{
				return this.entityData.Lastupdateddate; 
			}
			
			set
			{
				if (this.entityData.Lastupdateddate == value)
					return;
				
                OnPropertyChanging("Lastupdateddate");                    
				OnColumnChanging(BbCentreRegionlkpColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				this.entityData.Lastupdateddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCentreRegionlkpColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				OnPropertyChanged("Lastupdateddate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of BbCentre objects
		///	which are related to this object through the relation FK_bbCentre_bbCentreRegionlkp
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<BbCentre> BbCentreCollection
		{
			get { return entityData.BbCentreCollection; }
			set { entityData.BbCentreCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Centrereregion", "Centrereregion", 50));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Createdbyname", "Createdbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Createdbyname", "Createdbyname", 100));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Lastupdatedbyname", "Lastupdatedbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Lastupdatedbyname", "Lastupdatedbyname", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "bbCentreRegionlkp"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"centreregid", "centrereregion", "createdbyid", "createdbyname", "createddate", "lastupdatedbyid", "lastupdatedbyname", "lastupdateddate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as BbCentreRegionlkpEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (BbCentreRegionlkp) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<BbCentreRegionlkp>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as BbCentreRegionlkp);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed BbCentreRegionlkp Entity 
		///</summary>
		protected virtual BbCentreRegionlkp Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			BbCentreRegionlkp copy = new BbCentreRegionlkp();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Centreregid = this.Centreregid;
				copy.Centrereregion = this.Centrereregion;
				copy.Createdbyid = this.Createdbyid;
				copy.Createdbyname = this.Createdbyname;
				copy.Createddate = this.Createddate;
				copy.Lastupdatedbyid = this.Lastupdatedbyid;
				copy.Lastupdatedbyname = this.Lastupdatedbyname;
				copy.Lastupdateddate = this.Lastupdateddate;
			
		
			//deep copy nested objects
			copy.BbCentreCollection = (TList<BbCentre>) MakeCopyOf(this.BbCentreCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed BbCentreRegionlkp Entity 
		///</summary>
		public virtual BbCentreRegionlkp Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed BbCentreRegionlkp Entity which is a deep copy of the current entity.
		///</summary>
		public virtual BbCentreRegionlkp DeepCopy()
		{
			return EntityHelper.Clone<BbCentreRegionlkp>(this as BbCentreRegionlkp);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as BbCentreRegionlkpEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new BbCentreRegionlkpEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as BbCentreRegionlkpEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(BbCentreRegionlkpColumn column)
		{
			switch(column)
			{
					case BbCentreRegionlkpColumn.Centreregid:
					return entityData.Centreregid != _originalData.Centreregid;
					case BbCentreRegionlkpColumn.Centrereregion:
					return entityData.Centrereregion != _originalData.Centrereregion;
					case BbCentreRegionlkpColumn.Createdbyid:
					return entityData.Createdbyid != _originalData.Createdbyid;
					case BbCentreRegionlkpColumn.Createdbyname:
					return entityData.Createdbyname != _originalData.Createdbyname;
					case BbCentreRegionlkpColumn.Createddate:
					return entityData.Createddate != _originalData.Createddate;
					case BbCentreRegionlkpColumn.Lastupdatedbyid:
					return entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
					case BbCentreRegionlkpColumn.Lastupdatedbyname:
					return entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
					case BbCentreRegionlkpColumn.Lastupdateddate:
					return entityData.Lastupdateddate != _originalData.Lastupdateddate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< BbCentreRegionlkpColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Centreregid != _originalData.Centreregid;
			result = result || entityData.Centrereregion != _originalData.Centrereregion;
			result = result || entityData.Createdbyid != _originalData.Createdbyid;
			result = result || entityData.Createdbyname != _originalData.Createdbyname;
			result = result || entityData.Createddate != _originalData.Createddate;
			result = result || entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
			result = result || entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
			result = result || entityData.Lastupdateddate != _originalData.Lastupdateddate;
			return result;
		}	
		
		///<summary>
		///  Returns a BbCentreRegionlkp Entity with the original data.
		///</summary>
		public BbCentreRegionlkp GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateBbCentreRegionlkp(
				_originalData.Centrereregion,
				_originalData.Createdbyid,
				_originalData.Createdbyname,
				_originalData.Createddate,
				_originalData.Lastupdatedbyid,
				_originalData.Lastupdatedbyname,
				_originalData.Lastupdateddate
				);
				
			return (BbCentreRegionlkp)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="BbCentreRegionlkpBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is BbCentreRegionlkpBase)
				return ValueEquals(this, (BbCentreRegionlkpBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="BbCentreRegionlkpBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Centreregid.GetHashCode() ^ 
					((this.Centrereregion == null) ? string.Empty : this.Centrereregion.ToString()).GetHashCode() ^ 
					this.Createdbyid.GetHashCode() ^ 
					this.Createdbyname.GetHashCode() ^ 
					this.Createddate.GetHashCode() ^ 
					this.Lastupdatedbyid.GetHashCode() ^ 
					this.Lastupdatedbyname.GetHashCode() ^ 
					this.Lastupdateddate.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="BbCentreRegionlkpBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(BbCentreRegionlkpBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="BbCentreRegionlkpBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="BbCentreRegionlkpBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="BbCentreRegionlkpBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(BbCentreRegionlkpBase Object1, BbCentreRegionlkpBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Centreregid != Object2.Centreregid)
				equal = false;
			if ( Object1.Centrereregion != null && Object2.Centrereregion != null )
			{
				if (Object1.Centrereregion != Object2.Centrereregion)
					equal = false;
			}
			else if (Object1.Centrereregion == null ^ Object2.Centrereregion == null )
			{
				equal = false;
			}
			if (Object1.Createdbyid != Object2.Createdbyid)
				equal = false;
			if (Object1.Createdbyname != Object2.Createdbyname)
				equal = false;
			if (Object1.Createddate != Object2.Createddate)
				equal = false;
			if (Object1.Lastupdatedbyid != Object2.Lastupdatedbyid)
				equal = false;
			if (Object1.Lastupdatedbyname != Object2.Lastupdatedbyname)
				equal = false;
			if (Object1.Lastupdateddate != Object2.Lastupdateddate)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((BbCentreRegionlkpBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static BbCentreRegionlkpComparer GetComparer()
        {
            return new BbCentreRegionlkpComparer();
        }
        */

        // Comparer delegates back to BbCentreRegionlkp
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(BbCentreRegionlkp rhs, BbCentreRegionlkpColumn which)
        {
            switch (which)
            {
            	
            	
            	case BbCentreRegionlkpColumn.Centreregid:
            		return this.Centreregid.CompareTo(rhs.Centreregid);
            		
            		                 
            	
            	
            	case BbCentreRegionlkpColumn.Centrereregion:
            		return this.Centrereregion.CompareTo(rhs.Centrereregion);
            		
            		                 
            	
            	
            	case BbCentreRegionlkpColumn.Createdbyid:
            		return this.Createdbyid.CompareTo(rhs.Createdbyid);
            		
            		                 
            	
            	
            	case BbCentreRegionlkpColumn.Createdbyname:
            		return this.Createdbyname.CompareTo(rhs.Createdbyname);
            		
            		                 
            	
            	
            	case BbCentreRegionlkpColumn.Createddate:
            		return this.Createddate.CompareTo(rhs.Createddate);
            		
            		                 
            	
            	
            	case BbCentreRegionlkpColumn.Lastupdatedbyid:
            		return this.Lastupdatedbyid.CompareTo(rhs.Lastupdatedbyid);
            		
            		                 
            	
            	
            	case BbCentreRegionlkpColumn.Lastupdatedbyname:
            		return this.Lastupdatedbyname.CompareTo(rhs.Lastupdatedbyname);
            		
            		                 
            	
            	
            	case BbCentreRegionlkpColumn.Lastupdateddate:
            		return this.Lastupdateddate.CompareTo(rhs.Lastupdateddate);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<BbCentreRegionlkpKey> Members
		
		// member variable for the EntityId property
		private BbCentreRegionlkpKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual BbCentreRegionlkpKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new BbCentreRegionlkpKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("BbCentreRegionlkp")
					.Append("|").Append( this.Centreregid.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{9}{8}- Centreregid: {0}{8}- Centrereregion: {1}{8}- Createdbyid: {2}{8}- Createdbyname: {3}{8}- Createddate: {4}{8}- Lastupdatedbyid: {5}{8}- Lastupdatedbyname: {6}{8}- Lastupdateddate: {7}{8}{10}", 
				this.Centreregid,
				(this.Centrereregion == null) ? string.Empty : this.Centrereregion.ToString(),
				this.Createdbyid,
				this.Createdbyname,
				this.Createddate,
				this.Lastupdatedbyid,
				this.Lastupdatedbyname,
				this.Lastupdateddate,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'bbCentreRegionlkp' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class BbCentreRegionlkpEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// centreregid : Region Id
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "bbCentreRegionlkp"</remarks>
		public System.Int32 Centreregid;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// centrereregion : Region
		/// </summary>
		public System.String Centrereregion = null;
		
		/// <summary>
		/// createdbyid : Created by (id)
		/// </summary>
		public System.Int32 Createdbyid = (int)0;
		
		/// <summary>
		/// createdbyname : Created by
		/// </summary>
		public System.String Createdbyname = string.Empty;
		
		/// <summary>
		/// createddate : Date created
		/// </summary>
		public System.DateTime Createddate = DateTime.Now;
		
		/// <summary>
		/// lastupdatedbyid : Last updated by (id)
		/// </summary>
		public System.Int32 Lastupdatedbyid = (int)0;
		
		/// <summary>
		/// lastupdatedbyname : Last updated by
		/// </summary>
		public System.String Lastupdatedbyname = string.Empty;
		
		/// <summary>
		/// lastupdateddate : Date last updated
		/// </summary>
		public System.DateTime Lastupdateddate = DateTime.Now;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region BbCentreCollection
		
		private TList<BbCentre> _bbCentreCentreregionid;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _bbCentreCentreregionid
		/// </summary>
		
		public TList<BbCentre> BbCentreCollection
		{
			get
			{
				if (_bbCentreCentreregionid == null)
				{
				_bbCentreCentreregionid = new TList<BbCentre>();
				}
	
				return _bbCentreCentreregionid;
			}
			set { _bbCentreCentreregionid = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			BbCentreRegionlkpEntityData _tmp = new BbCentreRegionlkpEntityData();
						
			_tmp.Centreregid = this.Centreregid;
			
			_tmp.Centrereregion = this.Centrereregion;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._bbCentreCentreregionid != null)
				_tmp.BbCentreCollection = (TList<BbCentre>) MakeCopyOf(this.BbCentreCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			BbCentreRegionlkpEntityData _tmp = new BbCentreRegionlkpEntityData();
						
			_tmp.Centreregid = this.Centreregid;
			
			_tmp.Centrereregion = this.Centrereregion;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.BbCentreCollection = (TList<BbCentre>) MakeCopyOf(this.BbCentreCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbCentreRegionlkpColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(BbCentreRegionlkpColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbCentreRegionlkpColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(BbCentreRegionlkpColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbCentreRegionlkpColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(BbCentreRegionlkpColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				BbCentreRegionlkpEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new BbCentreRegionlkpEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbCentreRegionlkpColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(BbCentreRegionlkpColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				BbCentreRegionlkpEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new BbCentreRegionlkpEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region BbCentreRegionlkpEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="BbCentreRegionlkp"/> object.
	/// </remarks>
	public class BbCentreRegionlkpEventArgs : System.EventArgs
	{
		private BbCentreRegionlkpColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the BbCentreRegionlkpEventArgs class.
		///</summary>
		public BbCentreRegionlkpEventArgs(BbCentreRegionlkpColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the BbCentreRegionlkpEventArgs class.
		///</summary>
		public BbCentreRegionlkpEventArgs(BbCentreRegionlkpColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The BbCentreRegionlkpColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="BbCentreRegionlkpColumn" />
		public BbCentreRegionlkpColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all BbCentreRegionlkp related events.
	///</summary>
	public delegate void BbCentreRegionlkpEventHandler(object sender, BbCentreRegionlkpEventArgs e);
	
	#region BbCentreRegionlkpComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class BbCentreRegionlkpComparer : System.Collections.Generic.IComparer<BbCentreRegionlkp>
	{
		BbCentreRegionlkpColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:BbCentreRegionlkpComparer"/> class.
        /// </summary>
		public BbCentreRegionlkpComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:BbCentreRegionlkpComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public BbCentreRegionlkpComparer(BbCentreRegionlkpColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="BbCentreRegionlkp"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="BbCentreRegionlkp"/> to compare.</param>
        /// <param name="b">The second <c>BbCentreRegionlkp</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(BbCentreRegionlkp a, BbCentreRegionlkp b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(BbCentreRegionlkp entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(BbCentreRegionlkp a, BbCentreRegionlkp b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public BbCentreRegionlkpColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region BbCentreRegionlkpKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="BbCentreRegionlkp"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class BbCentreRegionlkpKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the BbCentreRegionlkpKey class.
		/// </summary>
		public BbCentreRegionlkpKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the BbCentreRegionlkpKey class.
		/// </summary>
		public BbCentreRegionlkpKey(BbCentreRegionlkpBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Centreregid = entity.Centreregid;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the BbCentreRegionlkpKey class.
		/// </summary>
		public BbCentreRegionlkpKey(System.Int32 _centreregid)
		{
			#region Init Properties

			this.Centreregid = _centreregid;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private BbCentreRegionlkpBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public BbCentreRegionlkpBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Centreregid property
		private System.Int32 _centreregid;
		
		/// <summary>
		/// Gets or sets the Centreregid property.
		/// </summary>
		public System.Int32 Centreregid
		{
			get { return _centreregid; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Centreregid = value;
				
				_centreregid = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Centreregid = ( values["Centreregid"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Centreregid"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Centreregid", Centreregid);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Centreregid: {0}{1}",
								Centreregid,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region BbCentreRegionlkpColumn Enum
	
	/// <summary>
	/// Enumerate the BbCentreRegionlkp columns.
	/// </summary>
	[Serializable]
	public enum BbCentreRegionlkpColumn : int
	{
		/// <summary>
		/// Centreregid : Region Id
		/// </summary>
		[EnumTextValue("Centreregid")]
		[ColumnEnum("centreregid", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		Centreregid = 1,
		/// <summary>
		/// Centrereregion : Region
		/// </summary>
		[EnumTextValue("Centrereregion")]
		[ColumnEnum("centrereregion", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		Centrereregion = 2,
		/// <summary>
		/// Createdbyid : Created by (id)
		/// </summary>
		[EnumTextValue("Createdbyid")]
		[ColumnEnum("createdbyid", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Createdbyid = 3,
		/// <summary>
		/// Createdbyname : Created by
		/// </summary>
		[EnumTextValue("Createdbyname")]
		[ColumnEnum("createdbyname", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 100)]
		Createdbyname = 4,
		/// <summary>
		/// Createddate : Date created
		/// </summary>
		[EnumTextValue("Createddate")]
		[ColumnEnum("createddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Createddate = 5,
		/// <summary>
		/// Lastupdatedbyid : Last updated by (id)
		/// </summary>
		[EnumTextValue("Lastupdatedbyid")]
		[ColumnEnum("lastupdatedbyid", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Lastupdatedbyid = 6,
		/// <summary>
		/// Lastupdatedbyname : Last updated by
		/// </summary>
		[EnumTextValue("Lastupdatedbyname")]
		[ColumnEnum("lastupdatedbyname", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 100)]
		Lastupdatedbyname = 7,
		/// <summary>
		/// Lastupdateddate : Date last updated
		/// </summary>
		[EnumTextValue("Lastupdateddate")]
		[ColumnEnum("lastupdateddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Lastupdateddate = 8
	}//End enum

	#endregion BbCentreRegionlkpColumn Enum

} // end namespace
