
/*
	File generated by NetTiers templates [www.nettiers.net]
	Generated on : 03 July 2020
	Important: Do not modify this file. Edit the file BbCommonFrequencylkp.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using MHS.Badbir.NetTiers.Entities.Validation;
#endregion

namespace MHS.Badbir.NetTiers.Entities
{
	///<summary>
	/// An object representation of the 'bbCommonFrequencylkp' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class BbCommonFrequencylkpBase : EntityBase, IBbCommonFrequencylkp, IEntityId<BbCommonFrequencylkpKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private BbCommonFrequencylkpEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private BbCommonFrequencylkpEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private BbCommonFrequencylkpEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<BbCommonFrequencylkp> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbCommonFrequencylkpEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbCommonFrequencylkpEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="BbCommonFrequencylkpBase"/> instance.
		///</summary>
		public BbCommonFrequencylkpBase()
		{
			this.entityData = new BbCommonFrequencylkpEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="BbCommonFrequencylkpBase"/> instance.
		///</summary>
		///<param name="_commonfrequency"></param>
		///<param name="_displayorder"></param>
		///<param name="_createdbyid">Created by (id)</param>
		///<param name="_createdbyname">Created by</param>
		///<param name="_createddate">Date created</param>
		///<param name="_lastupdatedbyid">Last updated by (id)</param>
		///<param name="_lastupdatedbyname">Last updated by</param>
		///<param name="_lastupdateddate">Date last updated</param>
		public BbCommonFrequencylkpBase(string _commonfrequency, int _displayorder, 
			int _createdbyid, string _createdbyname, System.DateTime _createddate, 
			int _lastupdatedbyid, string _lastupdatedbyname, System.DateTime _lastupdateddate)
		{
			this.entityData = new BbCommonFrequencylkpEntityData();
			this.backupData = null;

			this.Commonfrequency = _commonfrequency;
			this.Displayorder = _displayorder;
			this.Createdbyid = _createdbyid;
			this.Createdbyname = _createdbyname;
			this.Createddate = _createddate;
			this.Lastupdatedbyid = _lastupdatedbyid;
			this.Lastupdatedbyname = _lastupdatedbyname;
			this.Lastupdateddate = _lastupdateddate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="BbCommonFrequencylkp"/> instance.
		///</summary>
		///<param name="_commonfrequency"></param>
		///<param name="_displayorder"></param>
		///<param name="_createdbyid">Created by (id)</param>
		///<param name="_createdbyname">Created by</param>
		///<param name="_createddate">Date created</param>
		///<param name="_lastupdatedbyid">Last updated by (id)</param>
		///<param name="_lastupdatedbyname">Last updated by</param>
		///<param name="_lastupdateddate">Date last updated</param>
		public static BbCommonFrequencylkp CreateBbCommonFrequencylkp(string _commonfrequency, int _displayorder, 
			int _createdbyid, string _createdbyname, System.DateTime _createddate, 
			int _lastupdatedbyid, string _lastupdatedbyname, System.DateTime _lastupdateddate)
		{
			BbCommonFrequencylkp newBbCommonFrequencylkp = new BbCommonFrequencylkp();
			newBbCommonFrequencylkp.Commonfrequency = _commonfrequency;
			newBbCommonFrequencylkp.Displayorder = _displayorder;
			newBbCommonFrequencylkp.Createdbyid = _createdbyid;
			newBbCommonFrequencylkp.Createdbyname = _createdbyname;
			newBbCommonFrequencylkp.Createddate = _createddate;
			newBbCommonFrequencylkp.Lastupdatedbyid = _lastupdatedbyid;
			newBbCommonFrequencylkp.Lastupdatedbyname = _lastupdatedbyname;
			newBbCommonFrequencylkp.Lastupdateddate = _lastupdateddate;
			return newBbCommonFrequencylkp;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Commonfrequencyid property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual int Commonfrequencyid
		{
			get
			{
				return this.entityData.Commonfrequencyid; 
			}
			
			set
			{
				if (this.entityData.Commonfrequencyid == value)
					return;
				
                OnPropertyChanging("Commonfrequencyid");                    
				OnColumnChanging(BbCommonFrequencylkpColumn.Commonfrequencyid, this.entityData.Commonfrequencyid);
				this.entityData.Commonfrequencyid = value;
				this.EntityId.Commonfrequencyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCommonFrequencylkpColumn.Commonfrequencyid, this.entityData.Commonfrequencyid);
				OnPropertyChanged("Commonfrequencyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Commonfrequency property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public virtual string Commonfrequency
		{
			get
			{
				return this.entityData.Commonfrequency; 
			}
			
			set
			{
				if (this.entityData.Commonfrequency == value)
					return;
				
                OnPropertyChanging("Commonfrequency");                    
				OnColumnChanging(BbCommonFrequencylkpColumn.Commonfrequency, this.entityData.Commonfrequency);
				this.entityData.Commonfrequency = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCommonFrequencylkpColumn.Commonfrequency, this.entityData.Commonfrequency);
				OnPropertyChanged("Commonfrequency");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Displayorder property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Displayorder
		{
			get
			{
				return this.entityData.Displayorder; 
			}
			
			set
			{
				if (this.entityData.Displayorder == value)
					return;
				
                OnPropertyChanging("Displayorder");                    
				OnColumnChanging(BbCommonFrequencylkpColumn.Displayorder, this.entityData.Displayorder);
				this.entityData.Displayorder = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCommonFrequencylkpColumn.Displayorder, this.entityData.Displayorder);
				OnPropertyChanged("Displayorder");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyid property. 
		///		Created by (id)
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Created by (id)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Createdbyid
		{
			get
			{
				return this.entityData.Createdbyid; 
			}
			
			set
			{
				if (this.entityData.Createdbyid == value)
					return;
				
                OnPropertyChanging("Createdbyid");                    
				OnColumnChanging(BbCommonFrequencylkpColumn.Createdbyid, this.entityData.Createdbyid);
				this.entityData.Createdbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCommonFrequencylkpColumn.Createdbyid, this.entityData.Createdbyid);
				OnPropertyChanged("Createdbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyname property. 
		///		Created by
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@"Created by"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual string Createdbyname
		{
			get
			{
				return this.entityData.Createdbyname; 
			}
			
			set
			{
				if (this.entityData.Createdbyname == value)
					return;
				
                OnPropertyChanging("Createdbyname");                    
				OnColumnChanging(BbCommonFrequencylkpColumn.Createdbyname, this.entityData.Createdbyname);
				this.entityData.Createdbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCommonFrequencylkpColumn.Createdbyname, this.entityData.Createdbyname);
				OnPropertyChanged("Createdbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createddate property. 
		///		Date created
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Date created"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Createddate
		{
			get
			{
				return this.entityData.Createddate; 
			}
			
			set
			{
				if (this.entityData.Createddate == value)
					return;
				
                OnPropertyChanging("Createddate");                    
				OnColumnChanging(BbCommonFrequencylkpColumn.Createddate, this.entityData.Createddate);
				this.entityData.Createddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCommonFrequencylkpColumn.Createddate, this.entityData.Createddate);
				OnPropertyChanged("Createddate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyid property. 
		///		Last updated by (id)
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Last updated by (id)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Lastupdatedbyid
		{
			get
			{
				return this.entityData.Lastupdatedbyid; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyid == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyid");                    
				OnColumnChanging(BbCommonFrequencylkpColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				this.entityData.Lastupdatedbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCommonFrequencylkpColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				OnPropertyChanged("Lastupdatedbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyname property. 
		///		Last updated by
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@"Last updated by"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual string Lastupdatedbyname
		{
			get
			{
				return this.entityData.Lastupdatedbyname; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyname == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyname");                    
				OnColumnChanging(BbCommonFrequencylkpColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				this.entityData.Lastupdatedbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCommonFrequencylkpColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				OnPropertyChanged("Lastupdatedbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdateddate property. 
		///		Date last updated
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Date last updated"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Lastupdateddate
		{
			get
			{
				return this.entityData.Lastupdateddate; 
			}
			
			set
			{
				if (this.entityData.Lastupdateddate == value)
					return;
				
                OnPropertyChanging("Lastupdateddate");                    
				OnColumnChanging(BbCommonFrequencylkpColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				this.entityData.Lastupdateddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbCommonFrequencylkpColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				OnPropertyChanged("Lastupdateddate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of BbPatientdrug objects
		///	which are related to this object through the relation FK_bbPatientdrug_bbCommonFrequencylkp
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<BbPatientdrug> BbPatientdrugCollection
		{
			get { return entityData.BbPatientdrugCollection; }
			set { entityData.BbPatientdrugCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Commonfrequency", "Commonfrequency"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Commonfrequency", "Commonfrequency", 50));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Createdbyname", "Createdbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Createdbyname", "Createdbyname", 100));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Lastupdatedbyname", "Lastupdatedbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Lastupdatedbyname", "Lastupdatedbyname", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "bbCommonFrequencylkp"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"commonfrequencyid", "commonfrequency", "displayorder", "createdbyid", "createdbyname", "createddate", "lastupdatedbyid", "lastupdatedbyname", "lastupdateddate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as BbCommonFrequencylkpEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (BbCommonFrequencylkp) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<BbCommonFrequencylkp>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as BbCommonFrequencylkp);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed BbCommonFrequencylkp Entity 
		///</summary>
		protected virtual BbCommonFrequencylkp Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			BbCommonFrequencylkp copy = new BbCommonFrequencylkp();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Commonfrequencyid = this.Commonfrequencyid;
				copy.Commonfrequency = this.Commonfrequency;
				copy.Displayorder = this.Displayorder;
				copy.Createdbyid = this.Createdbyid;
				copy.Createdbyname = this.Createdbyname;
				copy.Createddate = this.Createddate;
				copy.Lastupdatedbyid = this.Lastupdatedbyid;
				copy.Lastupdatedbyname = this.Lastupdatedbyname;
				copy.Lastupdateddate = this.Lastupdateddate;
			
		
			//deep copy nested objects
			copy.BbPatientdrugCollection = (TList<BbPatientdrug>) MakeCopyOf(this.BbPatientdrugCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed BbCommonFrequencylkp Entity 
		///</summary>
		public virtual BbCommonFrequencylkp Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed BbCommonFrequencylkp Entity which is a deep copy of the current entity.
		///</summary>
		public virtual BbCommonFrequencylkp DeepCopy()
		{
			return EntityHelper.Clone<BbCommonFrequencylkp>(this as BbCommonFrequencylkp);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as BbCommonFrequencylkpEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new BbCommonFrequencylkpEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as BbCommonFrequencylkpEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(BbCommonFrequencylkpColumn column)
		{
			switch(column)
			{
					case BbCommonFrequencylkpColumn.Commonfrequencyid:
					return entityData.Commonfrequencyid != _originalData.Commonfrequencyid;
					case BbCommonFrequencylkpColumn.Commonfrequency:
					return entityData.Commonfrequency != _originalData.Commonfrequency;
					case BbCommonFrequencylkpColumn.Displayorder:
					return entityData.Displayorder != _originalData.Displayorder;
					case BbCommonFrequencylkpColumn.Createdbyid:
					return entityData.Createdbyid != _originalData.Createdbyid;
					case BbCommonFrequencylkpColumn.Createdbyname:
					return entityData.Createdbyname != _originalData.Createdbyname;
					case BbCommonFrequencylkpColumn.Createddate:
					return entityData.Createddate != _originalData.Createddate;
					case BbCommonFrequencylkpColumn.Lastupdatedbyid:
					return entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
					case BbCommonFrequencylkpColumn.Lastupdatedbyname:
					return entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
					case BbCommonFrequencylkpColumn.Lastupdateddate:
					return entityData.Lastupdateddate != _originalData.Lastupdateddate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< BbCommonFrequencylkpColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Commonfrequencyid != _originalData.Commonfrequencyid;
			result = result || entityData.Commonfrequency != _originalData.Commonfrequency;
			result = result || entityData.Displayorder != _originalData.Displayorder;
			result = result || entityData.Createdbyid != _originalData.Createdbyid;
			result = result || entityData.Createdbyname != _originalData.Createdbyname;
			result = result || entityData.Createddate != _originalData.Createddate;
			result = result || entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
			result = result || entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
			result = result || entityData.Lastupdateddate != _originalData.Lastupdateddate;
			return result;
		}	
		
		///<summary>
		///  Returns a BbCommonFrequencylkp Entity with the original data.
		///</summary>
		public BbCommonFrequencylkp GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateBbCommonFrequencylkp(
				_originalData.Commonfrequency,
				_originalData.Displayorder,
				_originalData.Createdbyid,
				_originalData.Createdbyname,
				_originalData.Createddate,
				_originalData.Lastupdatedbyid,
				_originalData.Lastupdatedbyname,
				_originalData.Lastupdateddate
				);
				
			return (BbCommonFrequencylkp)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="BbCommonFrequencylkpBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is BbCommonFrequencylkpBase)
				return ValueEquals(this, (BbCommonFrequencylkpBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="BbCommonFrequencylkpBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Commonfrequencyid.GetHashCode() ^ 
					this.Commonfrequency.GetHashCode() ^ 
					this.Displayorder.GetHashCode() ^ 
					this.Createdbyid.GetHashCode() ^ 
					this.Createdbyname.GetHashCode() ^ 
					this.Createddate.GetHashCode() ^ 
					this.Lastupdatedbyid.GetHashCode() ^ 
					this.Lastupdatedbyname.GetHashCode() ^ 
					this.Lastupdateddate.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="BbCommonFrequencylkpBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(BbCommonFrequencylkpBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="BbCommonFrequencylkpBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="BbCommonFrequencylkpBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="BbCommonFrequencylkpBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(BbCommonFrequencylkpBase Object1, BbCommonFrequencylkpBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Commonfrequencyid != Object2.Commonfrequencyid)
				equal = false;
			if (Object1.Commonfrequency != Object2.Commonfrequency)
				equal = false;
			if (Object1.Displayorder != Object2.Displayorder)
				equal = false;
			if (Object1.Createdbyid != Object2.Createdbyid)
				equal = false;
			if (Object1.Createdbyname != Object2.Createdbyname)
				equal = false;
			if (Object1.Createddate != Object2.Createddate)
				equal = false;
			if (Object1.Lastupdatedbyid != Object2.Lastupdatedbyid)
				equal = false;
			if (Object1.Lastupdatedbyname != Object2.Lastupdatedbyname)
				equal = false;
			if (Object1.Lastupdateddate != Object2.Lastupdateddate)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((BbCommonFrequencylkpBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static BbCommonFrequencylkpComparer GetComparer()
        {
            return new BbCommonFrequencylkpComparer();
        }
        */

        // Comparer delegates back to BbCommonFrequencylkp
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(BbCommonFrequencylkp rhs, BbCommonFrequencylkpColumn which)
        {
            switch (which)
            {
            	
            	
            	case BbCommonFrequencylkpColumn.Commonfrequencyid:
            		return this.Commonfrequencyid.CompareTo(rhs.Commonfrequencyid);
            		
            		                 
            	
            	
            	case BbCommonFrequencylkpColumn.Commonfrequency:
            		return this.Commonfrequency.CompareTo(rhs.Commonfrequency);
            		
            		                 
            	
            	
            	case BbCommonFrequencylkpColumn.Displayorder:
            		return this.Displayorder.CompareTo(rhs.Displayorder);
            		
            		                 
            	
            	
            	case BbCommonFrequencylkpColumn.Createdbyid:
            		return this.Createdbyid.CompareTo(rhs.Createdbyid);
            		
            		                 
            	
            	
            	case BbCommonFrequencylkpColumn.Createdbyname:
            		return this.Createdbyname.CompareTo(rhs.Createdbyname);
            		
            		                 
            	
            	
            	case BbCommonFrequencylkpColumn.Createddate:
            		return this.Createddate.CompareTo(rhs.Createddate);
            		
            		                 
            	
            	
            	case BbCommonFrequencylkpColumn.Lastupdatedbyid:
            		return this.Lastupdatedbyid.CompareTo(rhs.Lastupdatedbyid);
            		
            		                 
            	
            	
            	case BbCommonFrequencylkpColumn.Lastupdatedbyname:
            		return this.Lastupdatedbyname.CompareTo(rhs.Lastupdatedbyname);
            		
            		                 
            	
            	
            	case BbCommonFrequencylkpColumn.Lastupdateddate:
            		return this.Lastupdateddate.CompareTo(rhs.Lastupdateddate);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<BbCommonFrequencylkpKey> Members
		
		// member variable for the EntityId property
		private BbCommonFrequencylkpKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual BbCommonFrequencylkpKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new BbCommonFrequencylkpKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("BbCommonFrequencylkp")
					.Append("|").Append( this.Commonfrequencyid.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{10}{9}- Commonfrequencyid: {0}{9}- Commonfrequency: {1}{9}- Displayorder: {2}{9}- Createdbyid: {3}{9}- Createdbyname: {4}{9}- Createddate: {5}{9}- Lastupdatedbyid: {6}{9}- Lastupdatedbyname: {7}{9}- Lastupdateddate: {8}{9}{11}", 
				this.Commonfrequencyid,
				this.Commonfrequency,
				this.Displayorder,
				this.Createdbyid,
				this.Createdbyname,
				this.Createddate,
				this.Lastupdatedbyid,
				this.Lastupdatedbyname,
				this.Lastupdateddate,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'bbCommonFrequencylkp' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class BbCommonFrequencylkpEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// commonfrequencyid : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "bbCommonFrequencylkp"</remarks>
		public int Commonfrequencyid;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// commonfrequency : 
		/// </summary>
		public string Commonfrequency = string.Empty;
		
		/// <summary>
		/// displayorder : 
		/// </summary>
		public int Displayorder = (int)0;
		
		/// <summary>
		/// createdbyid : Created by (id)
		/// </summary>
		public int Createdbyid = (int)0;
		
		/// <summary>
		/// createdbyname : Created by
		/// </summary>
		public string Createdbyname = string.Empty;
		
		/// <summary>
		/// createddate : Date created
		/// </summary>
		public System.DateTime Createddate = DateTime.Now;
		
		/// <summary>
		/// lastupdatedbyid : Last updated by (id)
		/// </summary>
		public int Lastupdatedbyid = (int)0;
		
		/// <summary>
		/// lastupdatedbyname : Last updated by
		/// </summary>
		public string Lastupdatedbyname = string.Empty;
		
		/// <summary>
		/// lastupdateddate : Date last updated
		/// </summary>
		public System.DateTime Lastupdateddate = DateTime.Now;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region BbPatientdrugCollection
		
		private TList<BbPatientdrug> _bbPatientdrugCommonfrequencyid;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _bbPatientdrugCommonfrequencyid
		/// </summary>
		
		public TList<BbPatientdrug> BbPatientdrugCollection
		{
			get
			{
				if (_bbPatientdrugCommonfrequencyid == null)
				{
				_bbPatientdrugCommonfrequencyid = new TList<BbPatientdrug>();
				}
	
				return _bbPatientdrugCommonfrequencyid;
			}
			set { _bbPatientdrugCommonfrequencyid = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			BbCommonFrequencylkpEntityData _tmp = new BbCommonFrequencylkpEntityData();
						
			_tmp.Commonfrequencyid = this.Commonfrequencyid;
			
			_tmp.Commonfrequency = this.Commonfrequency;
			_tmp.Displayorder = this.Displayorder;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._bbPatientdrugCommonfrequencyid != null)
				_tmp.BbPatientdrugCollection = (TList<BbPatientdrug>) MakeCopyOf(this.BbPatientdrugCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			BbCommonFrequencylkpEntityData _tmp = new BbCommonFrequencylkpEntityData();
						
			_tmp.Commonfrequencyid = this.Commonfrequencyid;
			
			_tmp.Commonfrequency = this.Commonfrequency;
			_tmp.Displayorder = this.Displayorder;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.BbPatientdrugCollection = (TList<BbPatientdrug>) MakeCopyOf(this.BbPatientdrugCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbCommonFrequencylkpColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(BbCommonFrequencylkpColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbCommonFrequencylkpColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(BbCommonFrequencylkpColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbCommonFrequencylkpColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(BbCommonFrequencylkpColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				BbCommonFrequencylkpEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new BbCommonFrequencylkpEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbCommonFrequencylkpColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(BbCommonFrequencylkpColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				BbCommonFrequencylkpEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new BbCommonFrequencylkpEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region BbCommonFrequencylkpEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="BbCommonFrequencylkp"/> object.
	/// </remarks>
	public class BbCommonFrequencylkpEventArgs : System.EventArgs
	{
		private BbCommonFrequencylkpColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the BbCommonFrequencylkpEventArgs class.
		///</summary>
		public BbCommonFrequencylkpEventArgs(BbCommonFrequencylkpColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the BbCommonFrequencylkpEventArgs class.
		///</summary>
		public BbCommonFrequencylkpEventArgs(BbCommonFrequencylkpColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The BbCommonFrequencylkpColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="BbCommonFrequencylkpColumn" />
		public BbCommonFrequencylkpColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all BbCommonFrequencylkp related events.
	///</summary>
	public delegate void BbCommonFrequencylkpEventHandler(object sender, BbCommonFrequencylkpEventArgs e);
	
	#region BbCommonFrequencylkpComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class BbCommonFrequencylkpComparer : System.Collections.Generic.IComparer<BbCommonFrequencylkp>
	{
		BbCommonFrequencylkpColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:BbCommonFrequencylkpComparer"/> class.
        /// </summary>
		public BbCommonFrequencylkpComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:BbCommonFrequencylkpComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public BbCommonFrequencylkpComparer(BbCommonFrequencylkpColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="BbCommonFrequencylkp"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="BbCommonFrequencylkp"/> to compare.</param>
        /// <param name="b">The second <c>BbCommonFrequencylkp</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(BbCommonFrequencylkp a, BbCommonFrequencylkp b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(BbCommonFrequencylkp entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(BbCommonFrequencylkp a, BbCommonFrequencylkp b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public BbCommonFrequencylkpColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region BbCommonFrequencylkpKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="BbCommonFrequencylkp"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class BbCommonFrequencylkpKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the BbCommonFrequencylkpKey class.
		/// </summary>
		public BbCommonFrequencylkpKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the BbCommonFrequencylkpKey class.
		/// </summary>
		public BbCommonFrequencylkpKey(BbCommonFrequencylkpBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Commonfrequencyid = entity.Commonfrequencyid;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the BbCommonFrequencylkpKey class.
		/// </summary>
		public BbCommonFrequencylkpKey(int _commonfrequencyid)
		{
			#region Init Properties

			this.Commonfrequencyid = _commonfrequencyid;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private BbCommonFrequencylkpBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public BbCommonFrequencylkpBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Commonfrequencyid property
		private int _commonfrequencyid;
		
		/// <summary>
		/// Gets or sets the Commonfrequencyid property.
		/// </summary>
		public int Commonfrequencyid
		{
			get { return _commonfrequencyid; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Commonfrequencyid = value;
				
				_commonfrequencyid = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Commonfrequencyid = ( values["Commonfrequencyid"] != null ) ? (int) EntityUtil.ChangeType(values["Commonfrequencyid"], typeof(int)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Commonfrequencyid", Commonfrequencyid);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Commonfrequencyid: {0}{1}",
								Commonfrequencyid,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region BbCommonFrequencylkpColumn Enum
	
	/// <summary>
	/// Enumerate the BbCommonFrequencylkp columns.
	/// </summary>
	[Serializable]
	public enum BbCommonFrequencylkpColumn : int
	{
		/// <summary>
		/// Commonfrequencyid : 
		/// </summary>
		[EnumTextValue("Commonfrequencyid")]
		[ColumnEnum("commonfrequencyid", typeof(int), System.Data.DbType.Int32, true, true, false)]
		Commonfrequencyid = 1,
		/// <summary>
		/// Commonfrequency : 
		/// </summary>
		[EnumTextValue("Commonfrequency")]
		[ColumnEnum("commonfrequency", typeof(string), System.Data.DbType.AnsiString, false, false, false, 50)]
		Commonfrequency = 2,
		/// <summary>
		/// Displayorder : 
		/// </summary>
		[EnumTextValue("Displayorder")]
		[ColumnEnum("displayorder", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Displayorder = 3,
		/// <summary>
		/// Createdbyid : Created by (id)
		/// </summary>
		[EnumTextValue("Createdbyid")]
		[ColumnEnum("createdbyid", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Createdbyid = 4,
		/// <summary>
		/// Createdbyname : Created by
		/// </summary>
		[EnumTextValue("Createdbyname")]
		[ColumnEnum("createdbyname", typeof(string), System.Data.DbType.AnsiString, false, false, false, 100)]
		Createdbyname = 5,
		/// <summary>
		/// Createddate : Date created
		/// </summary>
		[EnumTextValue("Createddate")]
		[ColumnEnum("createddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Createddate = 6,
		/// <summary>
		/// Lastupdatedbyid : Last updated by (id)
		/// </summary>
		[EnumTextValue("Lastupdatedbyid")]
		[ColumnEnum("lastupdatedbyid", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Lastupdatedbyid = 7,
		/// <summary>
		/// Lastupdatedbyname : Last updated by
		/// </summary>
		[EnumTextValue("Lastupdatedbyname")]
		[ColumnEnum("lastupdatedbyname", typeof(string), System.Data.DbType.AnsiString, false, false, false, 100)]
		Lastupdatedbyname = 8,
		/// <summary>
		/// Lastupdateddate : Date last updated
		/// </summary>
		[EnumTextValue("Lastupdateddate")]
		[ColumnEnum("lastupdateddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Lastupdateddate = 9
	}//End enum

	#endregion BbCommonFrequencylkpColumn Enum

} // end namespace
