
/*
	File generated by NetTiers templates [www.nettiers.net]
	Generated on : 03 July 2020
	Important: Do not modify this file. Edit the file BbNotification.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using MHS.Badbir.NetTiers.Entities.Validation;
#endregion

namespace MHS.Badbir.NetTiers.Entities
{
	///<summary>
	/// An object representation of the 'bbNotification' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class BbNotificationBase : EntityBase, IBbNotification, IEntityId<BbNotificationKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private BbNotificationEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private BbNotificationEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private BbNotificationEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<BbNotification> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbNotificationEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbNotificationEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="BbNotificationBase"/> instance.
		///</summary>
		public BbNotificationBase()
		{
			this.entityData = new BbNotificationEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="BbNotificationBase"/> instance.
		///</summary>
		///<param name="_inboxId"></param>
		///<param name="_typeId"></param>
		///<param name="_unread"></param>
		///<param name="_dateRead"></param>
		///<param name="_statusId"></param>
		///<param name="_dateArchived"></param>
		///<param name="_groupId"></param>
		///<param name="_chid"></param>
		///<param name="_badbirUserId"></param>
		///<param name="_highPriority"></param>
		///<param name="_ntext"></param>
		///<param name="_include"></param>
		///<param name="_createdbyid"></param>
		///<param name="_createdbyname"></param>
		///<param name="_createddate"></param>
		///<param name="_lastupdatedbyid"></param>
		///<param name="_lastupdatedbyname"></param>
		///<param name="_lastupdateddate"></param>
		public BbNotificationBase(byte _inboxId, int _typeId, bool _unread, 
			System.DateTime? _dateRead, bool _statusId, System.DateTime? _dateArchived, System.Int32? _groupId, 
			System.Int32? _chid, System.Int32? _badbirUserId, bool _highPriority, string _ntext, 
			bool _include, int _createdbyid, string _createdbyname, System.DateTime _createddate, 
			int _lastupdatedbyid, string _lastupdatedbyname, System.DateTime _lastupdateddate)
		{
			this.entityData = new BbNotificationEntityData();
			this.backupData = null;

			this.InboxId = _inboxId;
			this.TypeId = _typeId;
			this.Unread = _unread;
			this.DateRead = _dateRead;
			this.StatusId = _statusId;
			this.DateArchived = _dateArchived;
			this.GroupId = _groupId;
			this.Chid = _chid;
			this.BadbirUserId = _badbirUserId;
			this.HighPriority = _highPriority;
			this.Ntext = _ntext;
			this.Include = _include;
			this.Createdbyid = _createdbyid;
			this.Createdbyname = _createdbyname;
			this.Createddate = _createddate;
			this.Lastupdatedbyid = _lastupdatedbyid;
			this.Lastupdatedbyname = _lastupdatedbyname;
			this.Lastupdateddate = _lastupdateddate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="BbNotification"/> instance.
		///</summary>
		///<param name="_inboxId"></param>
		///<param name="_typeId"></param>
		///<param name="_unread"></param>
		///<param name="_dateRead"></param>
		///<param name="_statusId"></param>
		///<param name="_dateArchived"></param>
		///<param name="_groupId"></param>
		///<param name="_chid"></param>
		///<param name="_badbirUserId"></param>
		///<param name="_highPriority"></param>
		///<param name="_ntext"></param>
		///<param name="_include"></param>
		///<param name="_createdbyid"></param>
		///<param name="_createdbyname"></param>
		///<param name="_createddate"></param>
		///<param name="_lastupdatedbyid"></param>
		///<param name="_lastupdatedbyname"></param>
		///<param name="_lastupdateddate"></param>
		public static BbNotification CreateBbNotification(byte _inboxId, int _typeId, bool _unread, 
			System.DateTime? _dateRead, bool _statusId, System.DateTime? _dateArchived, System.Int32? _groupId, 
			System.Int32? _chid, System.Int32? _badbirUserId, bool _highPriority, string _ntext, 
			bool _include, int _createdbyid, string _createdbyname, System.DateTime _createddate, 
			int _lastupdatedbyid, string _lastupdatedbyname, System.DateTime _lastupdateddate)
		{
			BbNotification newBbNotification = new BbNotification();
			newBbNotification.InboxId = _inboxId;
			newBbNotification.TypeId = _typeId;
			newBbNotification.Unread = _unread;
			newBbNotification.DateRead = _dateRead;
			newBbNotification.StatusId = _statusId;
			newBbNotification.DateArchived = _dateArchived;
			newBbNotification.GroupId = _groupId;
			newBbNotification.Chid = _chid;
			newBbNotification.BadbirUserId = _badbirUserId;
			newBbNotification.HighPriority = _highPriority;
			newBbNotification.Ntext = _ntext;
			newBbNotification.Include = _include;
			newBbNotification.Createdbyid = _createdbyid;
			newBbNotification.Createdbyname = _createdbyname;
			newBbNotification.Createddate = _createddate;
			newBbNotification.Lastupdatedbyid = _lastupdatedbyid;
			newBbNotification.Lastupdatedbyname = _lastupdatedbyname;
			newBbNotification.Lastupdateddate = _lastupdateddate;
			return newBbNotification;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Nid property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual int Nid
		{
			get
			{
				return this.entityData.Nid; 
			}
			
			set
			{
				if (this.entityData.Nid == value)
					return;
				
                OnPropertyChanging("Nid");                    
				OnColumnChanging(BbNotificationColumn.Nid, this.entityData.Nid);
				this.entityData.Nid = value;
				this.EntityId.Nid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Nid, this.entityData.Nid);
				OnPropertyChanged("Nid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the InboxId property. 
		///		
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual byte InboxId
		{
			get
			{
				return this.entityData.InboxId; 
			}
			
			set
			{
				if (this.entityData.InboxId == value)
					return;
				
                OnPropertyChanging("InboxId");                    
				OnColumnChanging(BbNotificationColumn.InboxId, this.entityData.InboxId);
				this.entityData.InboxId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.InboxId, this.entityData.InboxId);
				OnPropertyChanged("InboxId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TypeId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int TypeId
		{
			get
			{
				return this.entityData.TypeId; 
			}
			
			set
			{
				if (this.entityData.TypeId == value)
					return;
				
                OnPropertyChanging("TypeId");                    
				OnColumnChanging(BbNotificationColumn.TypeId, this.entityData.TypeId);
				this.entityData.TypeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.TypeId, this.entityData.TypeId);
				OnPropertyChanged("TypeId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Unread property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual bool Unread
		{
			get
			{
				return this.entityData.Unread; 
			}
			
			set
			{
				if (this.entityData.Unread == value)
					return;
				
                OnPropertyChanging("Unread");                    
				OnColumnChanging(BbNotificationColumn.Unread, this.entityData.Unread);
				this.entityData.Unread = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Unread, this.entityData.Unread);
				OnPropertyChanged("Unread");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DateRead property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? DateRead
		{
			get
			{
				return this.entityData.DateRead; 
			}
			
			set
			{
				if (this.entityData.DateRead == value)
					return;
				
                OnPropertyChanging("DateRead");                    
				OnColumnChanging(BbNotificationColumn.DateRead, this.entityData.DateRead);
				this.entityData.DateRead = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.DateRead, this.entityData.DateRead);
				OnPropertyChanged("DateRead");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the StatusId property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual bool StatusId
		{
			get
			{
				return this.entityData.StatusId; 
			}
			
			set
			{
				if (this.entityData.StatusId == value)
					return;
				
                OnPropertyChanging("StatusId");                    
				OnColumnChanging(BbNotificationColumn.StatusId, this.entityData.StatusId);
				this.entityData.StatusId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.StatusId, this.entityData.StatusId);
				OnPropertyChanged("StatusId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DateArchived property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? DateArchived
		{
			get
			{
				return this.entityData.DateArchived; 
			}
			
			set
			{
				if (this.entityData.DateArchived == value)
					return;
				
                OnPropertyChanging("DateArchived");                    
				OnColumnChanging(BbNotificationColumn.DateArchived, this.entityData.DateArchived);
				this.entityData.DateArchived = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.DateArchived, this.entityData.DateArchived);
				OnPropertyChanged("DateArchived");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the GroupId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? GroupId
		{
			get
			{
				return this.entityData.GroupId; 
			}
			
			set
			{
				if (this.entityData.GroupId == value)
					return;
				
                OnPropertyChanging("GroupId");                    
				OnColumnChanging(BbNotificationColumn.GroupId, this.entityData.GroupId);
				this.entityData.GroupId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.GroupId, this.entityData.GroupId);
				OnPropertyChanged("GroupId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Chid property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? Chid
		{
			get
			{
				return this.entityData.Chid; 
			}
			
			set
			{
				if (this.entityData.Chid == value)
					return;
				
                OnPropertyChanging("Chid");                    
				OnColumnChanging(BbNotificationColumn.Chid, this.entityData.Chid);
				this.entityData.Chid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Chid, this.entityData.Chid);
				OnPropertyChanged("Chid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the BadbirUserId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? BadbirUserId
		{
			get
			{
				return this.entityData.BadbirUserId; 
			}
			
			set
			{
				if (this.entityData.BadbirUserId == value)
					return;
				
                OnPropertyChanging("BadbirUserId");                    
				OnColumnChanging(BbNotificationColumn.BadbirUserId, this.entityData.BadbirUserId);
				this.entityData.BadbirUserId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.BadbirUserId, this.entityData.BadbirUserId);
				OnPropertyChanged("BadbirUserId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the HighPriority property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual bool HighPriority
		{
			get
			{
				return this.entityData.HighPriority; 
			}
			
			set
			{
				if (this.entityData.HighPriority == value)
					return;
				
                OnPropertyChanging("HighPriority");                    
				OnColumnChanging(BbNotificationColumn.HighPriority, this.entityData.HighPriority);
				this.entityData.HighPriority = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.HighPriority, this.entityData.HighPriority);
				OnPropertyChanged("HighPriority");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Ntext property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual string Ntext
		{
			get
			{
				return this.entityData.Ntext; 
			}
			
			set
			{
				if (this.entityData.Ntext == value)
					return;
				
                OnPropertyChanging("Ntext");                    
				OnColumnChanging(BbNotificationColumn.Ntext, this.entityData.Ntext);
				this.entityData.Ntext = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Ntext, this.entityData.Ntext);
				OnPropertyChanged("Ntext");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Include property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual bool Include
		{
			get
			{
				return this.entityData.Include; 
			}
			
			set
			{
				if (this.entityData.Include == value)
					return;
				
                OnPropertyChanging("Include");                    
				OnColumnChanging(BbNotificationColumn.Include, this.entityData.Include);
				this.entityData.Include = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Include, this.entityData.Include);
				OnPropertyChanged("Include");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyid property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Createdbyid
		{
			get
			{
				return this.entityData.Createdbyid; 
			}
			
			set
			{
				if (this.entityData.Createdbyid == value)
					return;
				
                OnPropertyChanging("Createdbyid");                    
				OnColumnChanging(BbNotificationColumn.Createdbyid, this.entityData.Createdbyid);
				this.entityData.Createdbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Createdbyid, this.entityData.Createdbyid);
				OnPropertyChanged("Createdbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyname property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual string Createdbyname
		{
			get
			{
				return this.entityData.Createdbyname; 
			}
			
			set
			{
				if (this.entityData.Createdbyname == value)
					return;
				
                OnPropertyChanging("Createdbyname");                    
				OnColumnChanging(BbNotificationColumn.Createdbyname, this.entityData.Createdbyname);
				this.entityData.Createdbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Createdbyname, this.entityData.Createdbyname);
				OnPropertyChanged("Createdbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createddate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Createddate
		{
			get
			{
				return this.entityData.Createddate; 
			}
			
			set
			{
				if (this.entityData.Createddate == value)
					return;
				
                OnPropertyChanging("Createddate");                    
				OnColumnChanging(BbNotificationColumn.Createddate, this.entityData.Createddate);
				this.entityData.Createddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Createddate, this.entityData.Createddate);
				OnPropertyChanged("Createddate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyid property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Lastupdatedbyid
		{
			get
			{
				return this.entityData.Lastupdatedbyid; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyid == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyid");                    
				OnColumnChanging(BbNotificationColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				this.entityData.Lastupdatedbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				OnPropertyChanged("Lastupdatedbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyname property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual string Lastupdatedbyname
		{
			get
			{
				return this.entityData.Lastupdatedbyname; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyname == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyname");                    
				OnColumnChanging(BbNotificationColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				this.entityData.Lastupdatedbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				OnPropertyChanged("Lastupdatedbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdateddate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Lastupdateddate
		{
			get
			{
				return this.entityData.Lastupdateddate; 
			}
			
			set
			{
				if (this.entityData.Lastupdateddate == value)
					return;
				
                OnPropertyChanging("Lastupdateddate");                    
				OnColumnChanging(BbNotificationColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				this.entityData.Lastupdateddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbNotificationColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				OnPropertyChanged("Lastupdateddate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="BbNotificationTypelkp"/>.
		/// </summary>
		/// <value>The source BbNotificationTypelkp for TypeId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual BbNotificationTypelkp TypeIdSource
      	{
            get { return entityData.TypeIdSource; }
            set { entityData.TypeIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Createdbyname", "Createdbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Createdbyname", "Createdbyname", 100));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Lastupdatedbyname", "Lastupdatedbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Lastupdatedbyname", "Lastupdatedbyname", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "bbNotification"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Nid", "InboxID", "TypeID", "Unread", "DateRead", "StatusID", "DateArchived", "GroupID", "Chid", "BADBIRUserID", "HighPriority", "NText", "include", "createdbyid", "createdbyname", "createddate", "lastupdatedbyid", "lastupdatedbyname", "lastupdateddate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as BbNotificationEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (BbNotification) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<BbNotification>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as BbNotification);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed BbNotification Entity 
		///</summary>
		protected virtual BbNotification Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			BbNotification copy = new BbNotification();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Nid = this.Nid;
				copy.InboxId = this.InboxId;
				copy.TypeId = this.TypeId;
				copy.Unread = this.Unread;
				copy.DateRead = this.DateRead;
				copy.StatusId = this.StatusId;
				copy.DateArchived = this.DateArchived;
				copy.GroupId = this.GroupId;
				copy.Chid = this.Chid;
				copy.BadbirUserId = this.BadbirUserId;
				copy.HighPriority = this.HighPriority;
				copy.Ntext = this.Ntext;
				copy.Include = this.Include;
				copy.Createdbyid = this.Createdbyid;
				copy.Createdbyname = this.Createdbyname;
				copy.Createddate = this.Createddate;
				copy.Lastupdatedbyid = this.Lastupdatedbyid;
				copy.Lastupdatedbyname = this.Lastupdatedbyname;
				copy.Lastupdateddate = this.Lastupdateddate;
			
			if (this.TypeIdSource != null && existingCopies.Contains(this.TypeIdSource))
				copy.TypeIdSource = existingCopies[this.TypeIdSource] as BbNotificationTypelkp;
			else
				copy.TypeIdSource = MakeCopyOf(this.TypeIdSource, existingCopies) as BbNotificationTypelkp;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed BbNotification Entity 
		///</summary>
		public virtual BbNotification Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed BbNotification Entity which is a deep copy of the current entity.
		///</summary>
		public virtual BbNotification DeepCopy()
		{
			return EntityHelper.Clone<BbNotification>(this as BbNotification);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as BbNotificationEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new BbNotificationEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as BbNotificationEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(BbNotificationColumn column)
		{
			switch(column)
			{
					case BbNotificationColumn.Nid:
					return entityData.Nid != _originalData.Nid;
					case BbNotificationColumn.InboxId:
					return entityData.InboxId != _originalData.InboxId;
					case BbNotificationColumn.TypeId:
					return entityData.TypeId != _originalData.TypeId;
					case BbNotificationColumn.Unread:
					return entityData.Unread != _originalData.Unread;
					case BbNotificationColumn.DateRead:
					return entityData.DateRead != _originalData.DateRead;
					case BbNotificationColumn.StatusId:
					return entityData.StatusId != _originalData.StatusId;
					case BbNotificationColumn.DateArchived:
					return entityData.DateArchived != _originalData.DateArchived;
					case BbNotificationColumn.GroupId:
					return entityData.GroupId != _originalData.GroupId;
					case BbNotificationColumn.Chid:
					return entityData.Chid != _originalData.Chid;
					case BbNotificationColumn.BadbirUserId:
					return entityData.BadbirUserId != _originalData.BadbirUserId;
					case BbNotificationColumn.HighPriority:
					return entityData.HighPriority != _originalData.HighPriority;
					case BbNotificationColumn.Ntext:
					return entityData.Ntext != _originalData.Ntext;
					case BbNotificationColumn.Include:
					return entityData.Include != _originalData.Include;
					case BbNotificationColumn.Createdbyid:
					return entityData.Createdbyid != _originalData.Createdbyid;
					case BbNotificationColumn.Createdbyname:
					return entityData.Createdbyname != _originalData.Createdbyname;
					case BbNotificationColumn.Createddate:
					return entityData.Createddate != _originalData.Createddate;
					case BbNotificationColumn.Lastupdatedbyid:
					return entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
					case BbNotificationColumn.Lastupdatedbyname:
					return entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
					case BbNotificationColumn.Lastupdateddate:
					return entityData.Lastupdateddate != _originalData.Lastupdateddate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< BbNotificationColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Nid != _originalData.Nid;
			result = result || entityData.InboxId != _originalData.InboxId;
			result = result || entityData.TypeId != _originalData.TypeId;
			result = result || entityData.Unread != _originalData.Unread;
			result = result || entityData.DateRead != _originalData.DateRead;
			result = result || entityData.StatusId != _originalData.StatusId;
			result = result || entityData.DateArchived != _originalData.DateArchived;
			result = result || entityData.GroupId != _originalData.GroupId;
			result = result || entityData.Chid != _originalData.Chid;
			result = result || entityData.BadbirUserId != _originalData.BadbirUserId;
			result = result || entityData.HighPriority != _originalData.HighPriority;
			result = result || entityData.Ntext != _originalData.Ntext;
			result = result || entityData.Include != _originalData.Include;
			result = result || entityData.Createdbyid != _originalData.Createdbyid;
			result = result || entityData.Createdbyname != _originalData.Createdbyname;
			result = result || entityData.Createddate != _originalData.Createddate;
			result = result || entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
			result = result || entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
			result = result || entityData.Lastupdateddate != _originalData.Lastupdateddate;
			return result;
		}	
		
		///<summary>
		///  Returns a BbNotification Entity with the original data.
		///</summary>
		public BbNotification GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateBbNotification(
				_originalData.InboxId,
				_originalData.TypeId,
				_originalData.Unread,
				_originalData.DateRead,
				_originalData.StatusId,
				_originalData.DateArchived,
				_originalData.GroupId,
				_originalData.Chid,
				_originalData.BadbirUserId,
				_originalData.HighPriority,
				_originalData.Ntext,
				_originalData.Include,
				_originalData.Createdbyid,
				_originalData.Createdbyname,
				_originalData.Createddate,
				_originalData.Lastupdatedbyid,
				_originalData.Lastupdatedbyname,
				_originalData.Lastupdateddate
				);
				
			return (BbNotification)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="BbNotificationBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is BbNotificationBase)
				return ValueEquals(this, (BbNotificationBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="BbNotificationBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Nid.GetHashCode() ^ 
					this.InboxId.GetHashCode() ^ 
					this.TypeId.GetHashCode() ^ 
					this.Unread.GetHashCode() ^ 
					((this.DateRead == null) ? string.Empty : this.DateRead.ToString()).GetHashCode() ^ 
					this.StatusId.GetHashCode() ^ 
					((this.DateArchived == null) ? string.Empty : this.DateArchived.ToString()).GetHashCode() ^ 
					((this.GroupId == null) ? string.Empty : this.GroupId.ToString()).GetHashCode() ^ 
					((this.Chid == null) ? string.Empty : this.Chid.ToString()).GetHashCode() ^ 
					((this.BadbirUserId == null) ? string.Empty : this.BadbirUserId.ToString()).GetHashCode() ^ 
					this.HighPriority.GetHashCode() ^ 
					((this.Ntext == null) ? string.Empty : this.Ntext.ToString()).GetHashCode() ^ 
					this.Include.GetHashCode() ^ 
					this.Createdbyid.GetHashCode() ^ 
					this.Createdbyname.GetHashCode() ^ 
					this.Createddate.GetHashCode() ^ 
					this.Lastupdatedbyid.GetHashCode() ^ 
					this.Lastupdatedbyname.GetHashCode() ^ 
					this.Lastupdateddate.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="BbNotificationBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(BbNotificationBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="BbNotificationBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="BbNotificationBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="BbNotificationBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(BbNotificationBase Object1, BbNotificationBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Nid != Object2.Nid)
				equal = false;
			if (Object1.InboxId != Object2.InboxId)
				equal = false;
			if (Object1.TypeId != Object2.TypeId)
				equal = false;
			if (Object1.Unread != Object2.Unread)
				equal = false;
			if ( Object1.DateRead != null && Object2.DateRead != null )
			{
				if (Object1.DateRead != Object2.DateRead)
					equal = false;
			}
			else if (Object1.DateRead == null ^ Object2.DateRead == null )
			{
				equal = false;
			}
			if (Object1.StatusId != Object2.StatusId)
				equal = false;
			if ( Object1.DateArchived != null && Object2.DateArchived != null )
			{
				if (Object1.DateArchived != Object2.DateArchived)
					equal = false;
			}
			else if (Object1.DateArchived == null ^ Object2.DateArchived == null )
			{
				equal = false;
			}
			if ( Object1.GroupId != null && Object2.GroupId != null )
			{
				if (Object1.GroupId != Object2.GroupId)
					equal = false;
			}
			else if (Object1.GroupId == null ^ Object2.GroupId == null )
			{
				equal = false;
			}
			if ( Object1.Chid != null && Object2.Chid != null )
			{
				if (Object1.Chid != Object2.Chid)
					equal = false;
			}
			else if (Object1.Chid == null ^ Object2.Chid == null )
			{
				equal = false;
			}
			if ( Object1.BadbirUserId != null && Object2.BadbirUserId != null )
			{
				if (Object1.BadbirUserId != Object2.BadbirUserId)
					equal = false;
			}
			else if (Object1.BadbirUserId == null ^ Object2.BadbirUserId == null )
			{
				equal = false;
			}
			if (Object1.HighPriority != Object2.HighPriority)
				equal = false;
			if ( Object1.Ntext != null && Object2.Ntext != null )
			{
				if (Object1.Ntext != Object2.Ntext)
					equal = false;
			}
			else if (Object1.Ntext == null ^ Object2.Ntext == null )
			{
				equal = false;
			}
			if (Object1.Include != Object2.Include)
				equal = false;
			if (Object1.Createdbyid != Object2.Createdbyid)
				equal = false;
			if (Object1.Createdbyname != Object2.Createdbyname)
				equal = false;
			if (Object1.Createddate != Object2.Createddate)
				equal = false;
			if (Object1.Lastupdatedbyid != Object2.Lastupdatedbyid)
				equal = false;
			if (Object1.Lastupdatedbyname != Object2.Lastupdatedbyname)
				equal = false;
			if (Object1.Lastupdateddate != Object2.Lastupdateddate)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((BbNotificationBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static BbNotificationComparer GetComparer()
        {
            return new BbNotificationComparer();
        }
        */

        // Comparer delegates back to BbNotification
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(BbNotification rhs, BbNotificationColumn which)
        {
            switch (which)
            {
            	
            	
            	case BbNotificationColumn.Nid:
            		return this.Nid.CompareTo(rhs.Nid);
            		
            		                 
            	
            	
            	case BbNotificationColumn.InboxId:
            		return this.InboxId.CompareTo(rhs.InboxId);
            		
            		                 
            	
            	
            	case BbNotificationColumn.TypeId:
            		return this.TypeId.CompareTo(rhs.TypeId);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Unread:
            		return this.Unread.CompareTo(rhs.Unread);
            		
            		                 
            	
            	
            	case BbNotificationColumn.DateRead:
            		return this.DateRead.Value.CompareTo(rhs.DateRead.Value);
            		
            		                 
            	
            	
            	case BbNotificationColumn.StatusId:
            		return this.StatusId.CompareTo(rhs.StatusId);
            		
            		                 
            	
            	
            	case BbNotificationColumn.DateArchived:
            		return this.DateArchived.Value.CompareTo(rhs.DateArchived.Value);
            		
            		                 
            	
            	
            	case BbNotificationColumn.GroupId:
            		return this.GroupId.Value.CompareTo(rhs.GroupId.Value);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Chid:
            		return this.Chid.Value.CompareTo(rhs.Chid.Value);
            		
            		                 
            	
            	
            	case BbNotificationColumn.BadbirUserId:
            		return this.BadbirUserId.Value.CompareTo(rhs.BadbirUserId.Value);
            		
            		                 
            	
            	
            	case BbNotificationColumn.HighPriority:
            		return this.HighPriority.CompareTo(rhs.HighPriority);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Ntext:
            		return this.Ntext.CompareTo(rhs.Ntext);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Include:
            		return this.Include.CompareTo(rhs.Include);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Createdbyid:
            		return this.Createdbyid.CompareTo(rhs.Createdbyid);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Createdbyname:
            		return this.Createdbyname.CompareTo(rhs.Createdbyname);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Createddate:
            		return this.Createddate.CompareTo(rhs.Createddate);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Lastupdatedbyid:
            		return this.Lastupdatedbyid.CompareTo(rhs.Lastupdatedbyid);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Lastupdatedbyname:
            		return this.Lastupdatedbyname.CompareTo(rhs.Lastupdatedbyname);
            		
            		                 
            	
            	
            	case BbNotificationColumn.Lastupdateddate:
            		return this.Lastupdateddate.CompareTo(rhs.Lastupdateddate);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<BbNotificationKey> Members
		
		// member variable for the EntityId property
		private BbNotificationKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual BbNotificationKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new BbNotificationKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("BbNotification")
					.Append("|").Append( this.Nid.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{20}{19}- Nid: {0}{19}- InboxId: {1}{19}- TypeId: {2}{19}- Unread: {3}{19}- DateRead: {4}{19}- StatusId: {5}{19}- DateArchived: {6}{19}- GroupId: {7}{19}- Chid: {8}{19}- BadbirUserId: {9}{19}- HighPriority: {10}{19}- Ntext: {11}{19}- Include: {12}{19}- Createdbyid: {13}{19}- Createdbyname: {14}{19}- Createddate: {15}{19}- Lastupdatedbyid: {16}{19}- Lastupdatedbyname: {17}{19}- Lastupdateddate: {18}{19}{21}", 
				this.Nid,
				this.InboxId,
				this.TypeId,
				this.Unread,
				(this.DateRead == null) ? string.Empty : this.DateRead.ToString(),
				this.StatusId,
				(this.DateArchived == null) ? string.Empty : this.DateArchived.ToString(),
				(this.GroupId == null) ? string.Empty : this.GroupId.ToString(),
				(this.Chid == null) ? string.Empty : this.Chid.ToString(),
				(this.BadbirUserId == null) ? string.Empty : this.BadbirUserId.ToString(),
				this.HighPriority,
				(this.Ntext == null) ? string.Empty : this.Ntext.ToString(),
				this.Include,
				this.Createdbyid,
				this.Createdbyname,
				this.Createddate,
				this.Lastupdatedbyid,
				this.Lastupdatedbyname,
				this.Lastupdateddate,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'bbNotification' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class BbNotificationEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Nid : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "bbNotification"</remarks>
		public int Nid;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// InboxID : 
		/// </summary>
		public byte InboxId = (byte)0;
		
		/// <summary>
		/// TypeID : 
		/// </summary>
		public int TypeId = (int)0;
		
		/// <summary>
		/// Unread : 
		/// </summary>
		public bool Unread = false;
		
		/// <summary>
		/// DateRead : 
		/// </summary>
		public System.DateTime? DateRead = null;
		
		/// <summary>
		/// StatusID : 
		/// </summary>
		public bool StatusId = false;
		
		/// <summary>
		/// DateArchived : 
		/// </summary>
		public System.DateTime? DateArchived = null;
		
		/// <summary>
		/// GroupID : 
		/// </summary>
		public System.Int32? GroupId = null;
		
		/// <summary>
		/// Chid : 
		/// </summary>
		public System.Int32? Chid = null;
		
		/// <summary>
		/// BADBIRUserID : 
		/// </summary>
		public System.Int32? BadbirUserId = null;
		
		/// <summary>
		/// HighPriority : 
		/// </summary>
		public bool HighPriority = false;
		
		/// <summary>
		/// NText : 
		/// </summary>
		public string Ntext = null;
		
		/// <summary>
		/// include : 
		/// </summary>
		public bool Include = true;
		
		/// <summary>
		/// createdbyid : 
		/// </summary>
		public int Createdbyid = (int)0;
		
		/// <summary>
		/// createdbyname : 
		/// </summary>
		public string Createdbyname = string.Empty;
		
		/// <summary>
		/// createddate : 
		/// </summary>
		public System.DateTime Createddate = DateTime.Now;
		
		/// <summary>
		/// lastupdatedbyid : 
		/// </summary>
		public int Lastupdatedbyid = (int)0;
		
		/// <summary>
		/// lastupdatedbyname : 
		/// </summary>
		public string Lastupdatedbyname = string.Empty;
		
		/// <summary>
		/// lastupdateddate : 
		/// </summary>
		public System.DateTime Lastupdateddate = DateTime.Now;
		#endregion
			
		#region Source Foreign Key Property
				
		private BbNotificationTypelkp _typeIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="BbNotificationTypelkp"/>.
		/// </summary>
		/// <value>The source BbNotificationTypelkp for TypeId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual BbNotificationTypelkp TypeIdSource
      	{
            get { return this._typeIdSource; }
            set { this._typeIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			BbNotificationEntityData _tmp = new BbNotificationEntityData();
						
			_tmp.Nid = this.Nid;
			
			_tmp.InboxId = this.InboxId;
			_tmp.TypeId = this.TypeId;
			_tmp.Unread = this.Unread;
			_tmp.DateRead = this.DateRead;
			_tmp.StatusId = this.StatusId;
			_tmp.DateArchived = this.DateArchived;
			_tmp.GroupId = this.GroupId;
			_tmp.Chid = this.Chid;
			_tmp.BadbirUserId = this.BadbirUserId;
			_tmp.HighPriority = this.HighPriority;
			_tmp.Ntext = this.Ntext;
			_tmp.Include = this.Include;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			
			#region Source Parent Composite Entities
			if (this.TypeIdSource != null)
				_tmp.TypeIdSource = MakeCopyOf(this.TypeIdSource) as BbNotificationTypelkp;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			BbNotificationEntityData _tmp = new BbNotificationEntityData();
						
			_tmp.Nid = this.Nid;
			
			_tmp.InboxId = this.InboxId;
			_tmp.TypeId = this.TypeId;
			_tmp.Unread = this.Unread;
			_tmp.DateRead = this.DateRead;
			_tmp.StatusId = this.StatusId;
			_tmp.DateArchived = this.DateArchived;
			_tmp.GroupId = this.GroupId;
			_tmp.Chid = this.Chid;
			_tmp.BadbirUserId = this.BadbirUserId;
			_tmp.HighPriority = this.HighPriority;
			_tmp.Ntext = this.Ntext;
			_tmp.Include = this.Include;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			
			#region Source Parent Composite Entities
			if (this.TypeIdSource != null && existingCopies.Contains(this.TypeIdSource))
				_tmp.TypeIdSource = existingCopies[this.TypeIdSource] as BbNotificationTypelkp;
			else
				_tmp.TypeIdSource = MakeCopyOf(this.TypeIdSource, existingCopies) as BbNotificationTypelkp;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbNotificationColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(BbNotificationColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbNotificationColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(BbNotificationColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbNotificationColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(BbNotificationColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				BbNotificationEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new BbNotificationEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbNotificationColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(BbNotificationColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				BbNotificationEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new BbNotificationEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region BbNotificationEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="BbNotification"/> object.
	/// </remarks>
	public class BbNotificationEventArgs : System.EventArgs
	{
		private BbNotificationColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the BbNotificationEventArgs class.
		///</summary>
		public BbNotificationEventArgs(BbNotificationColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the BbNotificationEventArgs class.
		///</summary>
		public BbNotificationEventArgs(BbNotificationColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The BbNotificationColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="BbNotificationColumn" />
		public BbNotificationColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all BbNotification related events.
	///</summary>
	public delegate void BbNotificationEventHandler(object sender, BbNotificationEventArgs e);
	
	#region BbNotificationComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class BbNotificationComparer : System.Collections.Generic.IComparer<BbNotification>
	{
		BbNotificationColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:BbNotificationComparer"/> class.
        /// </summary>
		public BbNotificationComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:BbNotificationComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public BbNotificationComparer(BbNotificationColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="BbNotification"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="BbNotification"/> to compare.</param>
        /// <param name="b">The second <c>BbNotification</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(BbNotification a, BbNotification b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(BbNotification entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(BbNotification a, BbNotification b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public BbNotificationColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region BbNotificationKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="BbNotification"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class BbNotificationKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the BbNotificationKey class.
		/// </summary>
		public BbNotificationKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the BbNotificationKey class.
		/// </summary>
		public BbNotificationKey(BbNotificationBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Nid = entity.Nid;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the BbNotificationKey class.
		/// </summary>
		public BbNotificationKey(int _nid)
		{
			#region Init Properties

			this.Nid = _nid;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private BbNotificationBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public BbNotificationBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Nid property
		private int _nid;
		
		/// <summary>
		/// Gets or sets the Nid property.
		/// </summary>
		public int Nid
		{
			get { return _nid; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Nid = value;
				
				_nid = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Nid = ( values["Nid"] != null ) ? (int) EntityUtil.ChangeType(values["Nid"], typeof(int)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Nid", Nid);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Nid: {0}{1}",
								Nid,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region BbNotificationColumn Enum
	
	/// <summary>
	/// Enumerate the BbNotification columns.
	/// </summary>
	[Serializable]
	public enum BbNotificationColumn : int
	{
		/// <summary>
		/// Nid : 
		/// </summary>
		[EnumTextValue("Nid")]
		[ColumnEnum("Nid", typeof(int), System.Data.DbType.Int32, true, true, false)]
		Nid = 1,
		/// <summary>
		/// InboxId : 
		/// </summary>
		[EnumTextValue("Inbox Id")]
		[ColumnEnum("InboxID", typeof(byte), System.Data.DbType.Byte, false, false, false)]
		InboxId = 2,
		/// <summary>
		/// TypeId : 
		/// </summary>
		[EnumTextValue("Type Id")]
		[ColumnEnum("TypeID", typeof(int), System.Data.DbType.Int32, false, false, false)]
		TypeId = 3,
		/// <summary>
		/// Unread : 
		/// </summary>
		[EnumTextValue("Unread")]
		[ColumnEnum("Unread", typeof(bool), System.Data.DbType.Boolean, false, false, false)]
		Unread = 4,
		/// <summary>
		/// DateRead : 
		/// </summary>
		[EnumTextValue("Date Read")]
		[ColumnEnum("DateRead", typeof(System.DateTime?), System.Data.DbType.DateTime, false, false, true)]
		DateRead = 5,
		/// <summary>
		/// StatusId : 
		/// </summary>
		[EnumTextValue("Status Id")]
		[ColumnEnum("StatusID", typeof(bool), System.Data.DbType.Boolean, false, false, false)]
		StatusId = 6,
		/// <summary>
		/// DateArchived : 
		/// </summary>
		[EnumTextValue("Date Archived")]
		[ColumnEnum("DateArchived", typeof(System.DateTime?), System.Data.DbType.DateTime, false, false, true)]
		DateArchived = 7,
		/// <summary>
		/// GroupId : 
		/// </summary>
		[EnumTextValue("Group Id")]
		[ColumnEnum("GroupID", typeof(System.Int32?), System.Data.DbType.Int32, false, false, true)]
		GroupId = 8,
		/// <summary>
		/// Chid : 
		/// </summary>
		[EnumTextValue("Chid")]
		[ColumnEnum("Chid", typeof(System.Int32?), System.Data.DbType.Int32, false, false, true)]
		Chid = 9,
		/// <summary>
		/// BadbirUserId : 
		/// </summary>
		[EnumTextValue("Badbir User Id")]
		[ColumnEnum("BADBIRUserID", typeof(System.Int32?), System.Data.DbType.Int32, false, false, true)]
		BadbirUserId = 10,
		/// <summary>
		/// HighPriority : 
		/// </summary>
		[EnumTextValue("High Priority")]
		[ColumnEnum("HighPriority", typeof(bool), System.Data.DbType.Boolean, false, false, false)]
		HighPriority = 11,
		/// <summary>
		/// Ntext : 
		/// </summary>
		[EnumTextValue("Ntext")]
		[ColumnEnum("NText", typeof(string), System.Data.DbType.AnsiString, false, false, true)]
		Ntext = 12,
		/// <summary>
		/// Include : 
		/// </summary>
		[EnumTextValue("Include")]
		[ColumnEnum("include", typeof(bool), System.Data.DbType.Boolean, false, false, false)]
		Include = 13,
		/// <summary>
		/// Createdbyid : 
		/// </summary>
		[EnumTextValue("Createdbyid")]
		[ColumnEnum("createdbyid", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Createdbyid = 14,
		/// <summary>
		/// Createdbyname : 
		/// </summary>
		[EnumTextValue("Createdbyname")]
		[ColumnEnum("createdbyname", typeof(string), System.Data.DbType.AnsiString, false, false, false, 100)]
		Createdbyname = 15,
		/// <summary>
		/// Createddate : 
		/// </summary>
		[EnumTextValue("Createddate")]
		[ColumnEnum("createddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Createddate = 16,
		/// <summary>
		/// Lastupdatedbyid : 
		/// </summary>
		[EnumTextValue("Lastupdatedbyid")]
		[ColumnEnum("lastupdatedbyid", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Lastupdatedbyid = 17,
		/// <summary>
		/// Lastupdatedbyname : 
		/// </summary>
		[EnumTextValue("Lastupdatedbyname")]
		[ColumnEnum("lastupdatedbyname", typeof(string), System.Data.DbType.AnsiString, false, false, false, 100)]
		Lastupdatedbyname = 18,
		/// <summary>
		/// Lastupdateddate : 
		/// </summary>
		[EnumTextValue("Lastupdateddate")]
		[ColumnEnum("lastupdateddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Lastupdateddate = 19
	}//End enum

	#endregion BbNotificationColumn Enum

} // end namespace
