
/*
	File generated by NetTiers templates [www.nettiers.net]
	Generated on : 03 July 2020
	Important: Do not modify this file. Edit the file BbQueryMessage.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using MHS.Badbir.NetTiers.Entities.Validation;
#endregion

namespace MHS.Badbir.NetTiers.Entities
{
	///<summary>
	/// An object representation of the 'bbQueryMessage' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class BbQueryMessageBase : EntityBase, IBbQueryMessage, IEntityId<BbQueryMessageKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private BbQueryMessageEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private BbQueryMessageEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private BbQueryMessageEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<BbQueryMessage> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbQueryMessageEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbQueryMessageEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="BbQueryMessageBase"/> instance.
		///</summary>
		public BbQueryMessageBase()
		{
			this.entityData = new BbQueryMessageEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="BbQueryMessageBase"/> instance.
		///</summary>
		///<param name="_qid">Query ID</param>
		///<param name="_message">Message</param>
		///<param name="_createdbyid">Created by (id)</param>
		///<param name="_createdbyname">Created by</param>
		///<param name="_createddate">Date created</param>
		///<param name="_lastupdatedbyid">Last updated by (id)</param>
		///<param name="_lastupdatedbyname">Last updated by</param>
		///<param name="_lastupdateddate">Date last updated</param>
		public BbQueryMessageBase(int _qid, string _message, int _createdbyid, 
			string _createdbyname, System.DateTime _createddate, int _lastupdatedbyid, string _lastupdatedbyname, 
			System.DateTime _lastupdateddate)
		{
			this.entityData = new BbQueryMessageEntityData();
			this.backupData = null;

			this.Qid = _qid;
			this.Message = _message;
			this.Createdbyid = _createdbyid;
			this.Createdbyname = _createdbyname;
			this.Createddate = _createddate;
			this.Lastupdatedbyid = _lastupdatedbyid;
			this.Lastupdatedbyname = _lastupdatedbyname;
			this.Lastupdateddate = _lastupdateddate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="BbQueryMessage"/> instance.
		///</summary>
		///<param name="_qid">Query ID</param>
		///<param name="_message">Message</param>
		///<param name="_createdbyid">Created by (id)</param>
		///<param name="_createdbyname">Created by</param>
		///<param name="_createddate">Date created</param>
		///<param name="_lastupdatedbyid">Last updated by (id)</param>
		///<param name="_lastupdatedbyname">Last updated by</param>
		///<param name="_lastupdateddate">Date last updated</param>
		public static BbQueryMessage CreateBbQueryMessage(int _qid, string _message, int _createdbyid, 
			string _createdbyname, System.DateTime _createddate, int _lastupdatedbyid, string _lastupdatedbyname, 
			System.DateTime _lastupdateddate)
		{
			BbQueryMessage newBbQueryMessage = new BbQueryMessage();
			newBbQueryMessage.Qid = _qid;
			newBbQueryMessage.Message = _message;
			newBbQueryMessage.Createdbyid = _createdbyid;
			newBbQueryMessage.Createdbyname = _createdbyname;
			newBbQueryMessage.Createddate = _createddate;
			newBbQueryMessage.Lastupdatedbyid = _lastupdatedbyid;
			newBbQueryMessage.Lastupdatedbyname = _lastupdatedbyname;
			newBbQueryMessage.Lastupdateddate = _lastupdateddate;
			return newBbQueryMessage;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the QmId property. 
		///		Query Message ID
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@"Query Message ID"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual int QmId
		{
			get
			{
				return this.entityData.QmId; 
			}
			
			set
			{
				if (this.entityData.QmId == value)
					return;
				
                OnPropertyChanging("QmId");                    
				OnColumnChanging(BbQueryMessageColumn.QmId, this.entityData.QmId);
				this.entityData.QmId = value;
				this.EntityId.QmId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryMessageColumn.QmId, this.entityData.QmId);
				OnPropertyChanged("QmId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Qid property. 
		///		Query ID
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Query ID"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Qid
		{
			get
			{
				return this.entityData.Qid; 
			}
			
			set
			{
				if (this.entityData.Qid == value)
					return;
				
                OnPropertyChanging("Qid");                    
				OnColumnChanging(BbQueryMessageColumn.Qid, this.entityData.Qid);
				this.entityData.Qid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryMessageColumn.Qid, this.entityData.Qid);
				OnPropertyChanged("Qid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Message property. 
		///		Message
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Message"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual string Message
		{
			get
			{
				return this.entityData.Message; 
			}
			
			set
			{
				if (this.entityData.Message == value)
					return;
				
                OnPropertyChanging("Message");                    
				OnColumnChanging(BbQueryMessageColumn.Message, this.entityData.Message);
				this.entityData.Message = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryMessageColumn.Message, this.entityData.Message);
				OnPropertyChanged("Message");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyid property. 
		///		Created by (id)
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Created by (id)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Createdbyid
		{
			get
			{
				return this.entityData.Createdbyid; 
			}
			
			set
			{
				if (this.entityData.Createdbyid == value)
					return;
				
                OnPropertyChanging("Createdbyid");                    
				OnColumnChanging(BbQueryMessageColumn.Createdbyid, this.entityData.Createdbyid);
				this.entityData.Createdbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryMessageColumn.Createdbyid, this.entityData.Createdbyid);
				OnPropertyChanged("Createdbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyname property. 
		///		Created by
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@"Created by"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual string Createdbyname
		{
			get
			{
				return this.entityData.Createdbyname; 
			}
			
			set
			{
				if (this.entityData.Createdbyname == value)
					return;
				
                OnPropertyChanging("Createdbyname");                    
				OnColumnChanging(BbQueryMessageColumn.Createdbyname, this.entityData.Createdbyname);
				this.entityData.Createdbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryMessageColumn.Createdbyname, this.entityData.Createdbyname);
				OnPropertyChanged("Createdbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createddate property. 
		///		Date created
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Date created"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Createddate
		{
			get
			{
				return this.entityData.Createddate; 
			}
			
			set
			{
				if (this.entityData.Createddate == value)
					return;
				
                OnPropertyChanging("Createddate");                    
				OnColumnChanging(BbQueryMessageColumn.Createddate, this.entityData.Createddate);
				this.entityData.Createddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryMessageColumn.Createddate, this.entityData.Createddate);
				OnPropertyChanged("Createddate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyid property. 
		///		Last updated by (id)
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Last updated by (id)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Lastupdatedbyid
		{
			get
			{
				return this.entityData.Lastupdatedbyid; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyid == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyid");                    
				OnColumnChanging(BbQueryMessageColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				this.entityData.Lastupdatedbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryMessageColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				OnPropertyChanged("Lastupdatedbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyname property. 
		///		Last updated by
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@"Last updated by"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual string Lastupdatedbyname
		{
			get
			{
				return this.entityData.Lastupdatedbyname; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyname == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyname");                    
				OnColumnChanging(BbQueryMessageColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				this.entityData.Lastupdatedbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryMessageColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				OnPropertyChanged("Lastupdatedbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdateddate property. 
		///		Date last updated
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Date last updated"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Lastupdateddate
		{
			get
			{
				return this.entityData.Lastupdateddate; 
			}
			
			set
			{
				if (this.entityData.Lastupdateddate == value)
					return;
				
                OnPropertyChanging("Lastupdateddate");                    
				OnColumnChanging(BbQueryMessageColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				this.entityData.Lastupdateddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryMessageColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				OnPropertyChanged("Lastupdateddate");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="BbQuery"/>.
		/// </summary>
		/// <value>The source BbQuery for Qid.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual BbQuery QidSource
      	{
            get { return entityData.QidSource; }
            set { entityData.QidSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Createdbyname", "Createdbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Createdbyname", "Createdbyname", 100));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Lastupdatedbyname", "Lastupdatedbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Lastupdatedbyname", "Lastupdatedbyname", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "bbQueryMessage"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"QMId", "QId", "message", "createdbyid", "createdbyname", "createddate", "lastupdatedbyid", "lastupdatedbyname", "lastupdateddate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as BbQueryMessageEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (BbQueryMessage) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<BbQueryMessage>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as BbQueryMessage);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed BbQueryMessage Entity 
		///</summary>
		protected virtual BbQueryMessage Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			BbQueryMessage copy = new BbQueryMessage();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.QmId = this.QmId;
				copy.Qid = this.Qid;
				copy.Message = this.Message;
				copy.Createdbyid = this.Createdbyid;
				copy.Createdbyname = this.Createdbyname;
				copy.Createddate = this.Createddate;
				copy.Lastupdatedbyid = this.Lastupdatedbyid;
				copy.Lastupdatedbyname = this.Lastupdatedbyname;
				copy.Lastupdateddate = this.Lastupdateddate;
			
			if (this.QidSource != null && existingCopies.Contains(this.QidSource))
				copy.QidSource = existingCopies[this.QidSource] as BbQuery;
			else
				copy.QidSource = MakeCopyOf(this.QidSource, existingCopies) as BbQuery;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed BbQueryMessage Entity 
		///</summary>
		public virtual BbQueryMessage Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed BbQueryMessage Entity which is a deep copy of the current entity.
		///</summary>
		public virtual BbQueryMessage DeepCopy()
		{
			return EntityHelper.Clone<BbQueryMessage>(this as BbQueryMessage);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as BbQueryMessageEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new BbQueryMessageEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as BbQueryMessageEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(BbQueryMessageColumn column)
		{
			switch(column)
			{
					case BbQueryMessageColumn.QmId:
					return entityData.QmId != _originalData.QmId;
					case BbQueryMessageColumn.Qid:
					return entityData.Qid != _originalData.Qid;
					case BbQueryMessageColumn.Message:
					return entityData.Message != _originalData.Message;
					case BbQueryMessageColumn.Createdbyid:
					return entityData.Createdbyid != _originalData.Createdbyid;
					case BbQueryMessageColumn.Createdbyname:
					return entityData.Createdbyname != _originalData.Createdbyname;
					case BbQueryMessageColumn.Createddate:
					return entityData.Createddate != _originalData.Createddate;
					case BbQueryMessageColumn.Lastupdatedbyid:
					return entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
					case BbQueryMessageColumn.Lastupdatedbyname:
					return entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
					case BbQueryMessageColumn.Lastupdateddate:
					return entityData.Lastupdateddate != _originalData.Lastupdateddate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< BbQueryMessageColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.QmId != _originalData.QmId;
			result = result || entityData.Qid != _originalData.Qid;
			result = result || entityData.Message != _originalData.Message;
			result = result || entityData.Createdbyid != _originalData.Createdbyid;
			result = result || entityData.Createdbyname != _originalData.Createdbyname;
			result = result || entityData.Createddate != _originalData.Createddate;
			result = result || entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
			result = result || entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
			result = result || entityData.Lastupdateddate != _originalData.Lastupdateddate;
			return result;
		}	
		
		///<summary>
		///  Returns a BbQueryMessage Entity with the original data.
		///</summary>
		public BbQueryMessage GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateBbQueryMessage(
				_originalData.Qid,
				_originalData.Message,
				_originalData.Createdbyid,
				_originalData.Createdbyname,
				_originalData.Createddate,
				_originalData.Lastupdatedbyid,
				_originalData.Lastupdatedbyname,
				_originalData.Lastupdateddate
				);
				
			return (BbQueryMessage)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="BbQueryMessageBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is BbQueryMessageBase)
				return ValueEquals(this, (BbQueryMessageBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="BbQueryMessageBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.QmId.GetHashCode() ^ 
					this.Qid.GetHashCode() ^ 
					((this.Message == null) ? string.Empty : this.Message.ToString()).GetHashCode() ^ 
					this.Createdbyid.GetHashCode() ^ 
					this.Createdbyname.GetHashCode() ^ 
					this.Createddate.GetHashCode() ^ 
					this.Lastupdatedbyid.GetHashCode() ^ 
					this.Lastupdatedbyname.GetHashCode() ^ 
					this.Lastupdateddate.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="BbQueryMessageBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(BbQueryMessageBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="BbQueryMessageBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="BbQueryMessageBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="BbQueryMessageBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(BbQueryMessageBase Object1, BbQueryMessageBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.QmId != Object2.QmId)
				equal = false;
			if (Object1.Qid != Object2.Qid)
				equal = false;
			if ( Object1.Message != null && Object2.Message != null )
			{
				if (Object1.Message != Object2.Message)
					equal = false;
			}
			else if (Object1.Message == null ^ Object2.Message == null )
			{
				equal = false;
			}
			if (Object1.Createdbyid != Object2.Createdbyid)
				equal = false;
			if (Object1.Createdbyname != Object2.Createdbyname)
				equal = false;
			if (Object1.Createddate != Object2.Createddate)
				equal = false;
			if (Object1.Lastupdatedbyid != Object2.Lastupdatedbyid)
				equal = false;
			if (Object1.Lastupdatedbyname != Object2.Lastupdatedbyname)
				equal = false;
			if (Object1.Lastupdateddate != Object2.Lastupdateddate)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((BbQueryMessageBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static BbQueryMessageComparer GetComparer()
        {
            return new BbQueryMessageComparer();
        }
        */

        // Comparer delegates back to BbQueryMessage
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(BbQueryMessage rhs, BbQueryMessageColumn which)
        {
            switch (which)
            {
            	
            	
            	case BbQueryMessageColumn.QmId:
            		return this.QmId.CompareTo(rhs.QmId);
            		
            		                 
            	
            	
            	case BbQueryMessageColumn.Qid:
            		return this.Qid.CompareTo(rhs.Qid);
            		
            		                 
            	
            	
            	case BbQueryMessageColumn.Message:
            		return this.Message.CompareTo(rhs.Message);
            		
            		                 
            	
            	
            	case BbQueryMessageColumn.Createdbyid:
            		return this.Createdbyid.CompareTo(rhs.Createdbyid);
            		
            		                 
            	
            	
            	case BbQueryMessageColumn.Createdbyname:
            		return this.Createdbyname.CompareTo(rhs.Createdbyname);
            		
            		                 
            	
            	
            	case BbQueryMessageColumn.Createddate:
            		return this.Createddate.CompareTo(rhs.Createddate);
            		
            		                 
            	
            	
            	case BbQueryMessageColumn.Lastupdatedbyid:
            		return this.Lastupdatedbyid.CompareTo(rhs.Lastupdatedbyid);
            		
            		                 
            	
            	
            	case BbQueryMessageColumn.Lastupdatedbyname:
            		return this.Lastupdatedbyname.CompareTo(rhs.Lastupdatedbyname);
            		
            		                 
            	
            	
            	case BbQueryMessageColumn.Lastupdateddate:
            		return this.Lastupdateddate.CompareTo(rhs.Lastupdateddate);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<BbQueryMessageKey> Members
		
		// member variable for the EntityId property
		private BbQueryMessageKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual BbQueryMessageKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new BbQueryMessageKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("BbQueryMessage")
					.Append("|").Append( this.QmId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{10}{9}- QmId: {0}{9}- Qid: {1}{9}- Message: {2}{9}- Createdbyid: {3}{9}- Createdbyname: {4}{9}- Createddate: {5}{9}- Lastupdatedbyid: {6}{9}- Lastupdatedbyname: {7}{9}- Lastupdateddate: {8}{9}{11}", 
				this.QmId,
				this.Qid,
				(this.Message == null) ? string.Empty : this.Message.ToString(),
				this.Createdbyid,
				this.Createdbyname,
				this.Createddate,
				this.Lastupdatedbyid,
				this.Lastupdatedbyname,
				this.Lastupdateddate,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'bbQueryMessage' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class BbQueryMessageEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// QMId : Query Message ID
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "bbQueryMessage"</remarks>
		public int QmId;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// QId : Query ID
		/// </summary>
		public int Qid = (int)0;
		
		/// <summary>
		/// message : Message
		/// </summary>
		public string Message = null;
		
		/// <summary>
		/// createdbyid : Created by (id)
		/// </summary>
		public int Createdbyid = (int)0;
		
		/// <summary>
		/// createdbyname : Created by
		/// </summary>
		public string Createdbyname = string.Empty;
		
		/// <summary>
		/// createddate : Date created
		/// </summary>
		public System.DateTime Createddate = DateTime.Now;
		
		/// <summary>
		/// lastupdatedbyid : Last updated by (id)
		/// </summary>
		public int Lastupdatedbyid = (int)0;
		
		/// <summary>
		/// lastupdatedbyname : Last updated by
		/// </summary>
		public string Lastupdatedbyname = string.Empty;
		
		/// <summary>
		/// lastupdateddate : Date last updated
		/// </summary>
		public System.DateTime Lastupdateddate = DateTime.Now;
		#endregion
			
		#region Source Foreign Key Property
				
		private BbQuery _qidSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="BbQuery"/>.
		/// </summary>
		/// <value>The source BbQuery for Qid.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual BbQuery QidSource
      	{
            get { return this._qidSource; }
            set { this._qidSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			BbQueryMessageEntityData _tmp = new BbQueryMessageEntityData();
						
			_tmp.QmId = this.QmId;
			
			_tmp.Qid = this.Qid;
			_tmp.Message = this.Message;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			
			#region Source Parent Composite Entities
			if (this.QidSource != null)
				_tmp.QidSource = MakeCopyOf(this.QidSource) as BbQuery;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			BbQueryMessageEntityData _tmp = new BbQueryMessageEntityData();
						
			_tmp.QmId = this.QmId;
			
			_tmp.Qid = this.Qid;
			_tmp.Message = this.Message;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			
			#region Source Parent Composite Entities
			if (this.QidSource != null && existingCopies.Contains(this.QidSource))
				_tmp.QidSource = existingCopies[this.QidSource] as BbQuery;
			else
				_tmp.QidSource = MakeCopyOf(this.QidSource, existingCopies) as BbQuery;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbQueryMessageColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(BbQueryMessageColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbQueryMessageColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(BbQueryMessageColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbQueryMessageColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(BbQueryMessageColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				BbQueryMessageEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new BbQueryMessageEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbQueryMessageColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(BbQueryMessageColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				BbQueryMessageEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new BbQueryMessageEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region BbQueryMessageEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="BbQueryMessage"/> object.
	/// </remarks>
	public class BbQueryMessageEventArgs : System.EventArgs
	{
		private BbQueryMessageColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the BbQueryMessageEventArgs class.
		///</summary>
		public BbQueryMessageEventArgs(BbQueryMessageColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the BbQueryMessageEventArgs class.
		///</summary>
		public BbQueryMessageEventArgs(BbQueryMessageColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The BbQueryMessageColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="BbQueryMessageColumn" />
		public BbQueryMessageColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all BbQueryMessage related events.
	///</summary>
	public delegate void BbQueryMessageEventHandler(object sender, BbQueryMessageEventArgs e);
	
	#region BbQueryMessageComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class BbQueryMessageComparer : System.Collections.Generic.IComparer<BbQueryMessage>
	{
		BbQueryMessageColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:BbQueryMessageComparer"/> class.
        /// </summary>
		public BbQueryMessageComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:BbQueryMessageComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public BbQueryMessageComparer(BbQueryMessageColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="BbQueryMessage"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="BbQueryMessage"/> to compare.</param>
        /// <param name="b">The second <c>BbQueryMessage</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(BbQueryMessage a, BbQueryMessage b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(BbQueryMessage entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(BbQueryMessage a, BbQueryMessage b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public BbQueryMessageColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region BbQueryMessageKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="BbQueryMessage"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class BbQueryMessageKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the BbQueryMessageKey class.
		/// </summary>
		public BbQueryMessageKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the BbQueryMessageKey class.
		/// </summary>
		public BbQueryMessageKey(BbQueryMessageBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.QmId = entity.QmId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the BbQueryMessageKey class.
		/// </summary>
		public BbQueryMessageKey(int _qmId)
		{
			#region Init Properties

			this.QmId = _qmId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private BbQueryMessageBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public BbQueryMessageBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the QmId property
		private int _qmId;
		
		/// <summary>
		/// Gets or sets the QmId property.
		/// </summary>
		public int QmId
		{
			get { return _qmId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.QmId = value;
				
				_qmId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				QmId = ( values["QmId"] != null ) ? (int) EntityUtil.ChangeType(values["QmId"], typeof(int)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("QmId", QmId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("QmId: {0}{1}",
								QmId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region BbQueryMessageColumn Enum
	
	/// <summary>
	/// Enumerate the BbQueryMessage columns.
	/// </summary>
	[Serializable]
	public enum BbQueryMessageColumn : int
	{
		/// <summary>
		/// QmId : Query Message ID
		/// </summary>
		[EnumTextValue("Qm Id")]
		[ColumnEnum("QMId", typeof(int), System.Data.DbType.Int32, true, true, false)]
		QmId = 1,
		/// <summary>
		/// Qid : Query ID
		/// </summary>
		[EnumTextValue("Qid")]
		[ColumnEnum("QId", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Qid = 2,
		/// <summary>
		/// Message : Message
		/// </summary>
		[EnumTextValue("Message")]
		[ColumnEnum("message", typeof(string), System.Data.DbType.AnsiString, false, false, true)]
		Message = 3,
		/// <summary>
		/// Createdbyid : Created by (id)
		/// </summary>
		[EnumTextValue("Createdbyid")]
		[ColumnEnum("createdbyid", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Createdbyid = 4,
		/// <summary>
		/// Createdbyname : Created by
		/// </summary>
		[EnumTextValue("Createdbyname")]
		[ColumnEnum("createdbyname", typeof(string), System.Data.DbType.AnsiString, false, false, false, 100)]
		Createdbyname = 5,
		/// <summary>
		/// Createddate : Date created
		/// </summary>
		[EnumTextValue("Createddate")]
		[ColumnEnum("createddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Createddate = 6,
		/// <summary>
		/// Lastupdatedbyid : Last updated by (id)
		/// </summary>
		[EnumTextValue("Lastupdatedbyid")]
		[ColumnEnum("lastupdatedbyid", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Lastupdatedbyid = 7,
		/// <summary>
		/// Lastupdatedbyname : Last updated by
		/// </summary>
		[EnumTextValue("Lastupdatedbyname")]
		[ColumnEnum("lastupdatedbyname", typeof(string), System.Data.DbType.AnsiString, false, false, false, 100)]
		Lastupdatedbyname = 8,
		/// <summary>
		/// Lastupdateddate : Date last updated
		/// </summary>
		[EnumTextValue("Lastupdateddate")]
		[ColumnEnum("lastupdateddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Lastupdateddate = 9
	}//End enum

	#endregion BbQueryMessageColumn Enum

} // end namespace
