
/*
	File generated by NetTiers templates [www.nettiers.net]
	Generated on : 03 July 2020
	Important: Do not modify this file. Edit the file BbQueryForCentre.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using MHS.Badbir.NetTiers.Entities.Validation;
#endregion

namespace MHS.Badbir.NetTiers.Entities
{
	///<summary>
	/// This table stores all queries, their related flags, subject and linked ids to other tables. Adverse Events are linked by a many to many link in a separate Link table.	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class BbQueryForCentreBase : EntityBase, IBbQueryForCentre, IEntityId<BbQueryForCentreKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private BbQueryForCentreEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private BbQueryForCentreEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private BbQueryForCentreEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<BbQueryForCentre> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbQueryForCentreEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BbQueryForCentreEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="BbQueryForCentreBase"/> instance.
		///</summary>
		public BbQueryForCentreBase()
		{
			this.entityData = new BbQueryForCentreEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="BbQueryForCentreBase"/> instance.
		///</summary>
		///<param name="_centreid">Centre ID to separate queries by centre</param>
		///<param name="_messagecount">number of responses added to the query</param>
		///<param name="_adminunread">Has any admin read (opened) it?
		/// 		/// 0=Yes (Admin has read it)
		/// 		/// 1=No (Admin has not read it)</param>
		///<param name="_clinicianunread">Has any clinician (opened) it?
		/// 		/// 0=Yes (Clinician has opened it)
		/// 		/// 1=No (Clinician hasn't opened it)</param>
		///<param name="_queryTypeId">Query Type ID (Foreign Key) Links to the table that contains all query types</param>
		///<param name="_queryStatusId">Query Status ID (Foreign Key) Links to the table that contain all query statuses</param>
		///<param name="_include">Is this a valid query?
		/// 		/// 0=No
		/// 		/// 1=Yes</param>
		///<param name="_createdbyid">Created by (id)</param>
		///<param name="_createdbyname">Created by</param>
		///<param name="_createddate">Date created</param>
		///<param name="_lastupdatedbyid">Last updated by (id) (including any responses)</param>
		///<param name="_lastupdatedbyname">Last updated by (Including any responses)</param>
		///<param name="_lastupdateddate">Date last updated (including any responses)</param>
		///<param name="_subject">Query Text</param>
		///<param name="_secondRequest">Is this a high priority query?
		/// 		/// 0=No
		/// 		/// 1=Yes</param>
		public BbQueryForCentreBase(int _centreid, int _messagecount, bool _adminunread, 
			bool _clinicianunread, int _queryTypeId, int _queryStatusId, bool _include, 
			int _createdbyid, string _createdbyname, System.DateTime _createddate, int _lastupdatedbyid, 
			string _lastupdatedbyname, System.DateTime _lastupdateddate, string _subject, 
			System.Boolean? _secondRequest)
		{
			this.entityData = new BbQueryForCentreEntityData();
			this.backupData = null;

			this.Centreid = _centreid;
			this.Messagecount = _messagecount;
			this.Adminunread = _adminunread;
			this.Clinicianunread = _clinicianunread;
			this.QueryTypeId = _queryTypeId;
			this.QueryStatusId = _queryStatusId;
			this.Include = _include;
			this.Createdbyid = _createdbyid;
			this.Createdbyname = _createdbyname;
			this.Createddate = _createddate;
			this.Lastupdatedbyid = _lastupdatedbyid;
			this.Lastupdatedbyname = _lastupdatedbyname;
			this.Lastupdateddate = _lastupdateddate;
			this.Subject = _subject;
			this.SecondRequest = _secondRequest;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="BbQueryForCentre"/> instance.
		///</summary>
		///<param name="_centreid">Centre ID to separate queries by centre</param>
		///<param name="_messagecount">number of responses added to the query</param>
		///<param name="_adminunread">Has any admin read (opened) it?
		/// 		/// 0=Yes (Admin has read it)
		/// 		/// 1=No (Admin has not read it)</param>
		///<param name="_clinicianunread">Has any clinician (opened) it?
		/// 		/// 0=Yes (Clinician has opened it)
		/// 		/// 1=No (Clinician hasn't opened it)</param>
		///<param name="_queryTypeId">Query Type ID (Foreign Key) Links to the table that contains all query types</param>
		///<param name="_queryStatusId">Query Status ID (Foreign Key) Links to the table that contain all query statuses</param>
		///<param name="_include">Is this a valid query?
		/// 		/// 0=No
		/// 		/// 1=Yes</param>
		///<param name="_createdbyid">Created by (id)</param>
		///<param name="_createdbyname">Created by</param>
		///<param name="_createddate">Date created</param>
		///<param name="_lastupdatedbyid">Last updated by (id) (including any responses)</param>
		///<param name="_lastupdatedbyname">Last updated by (Including any responses)</param>
		///<param name="_lastupdateddate">Date last updated (including any responses)</param>
		///<param name="_subject">Query Text</param>
		///<param name="_secondRequest">Is this a high priority query?
		/// 		/// 0=No
		/// 		/// 1=Yes</param>
		public static BbQueryForCentre CreateBbQueryForCentre(int _centreid, int _messagecount, bool _adminunread, 
			bool _clinicianunread, int _queryTypeId, int _queryStatusId, bool _include, 
			int _createdbyid, string _createdbyname, System.DateTime _createddate, int _lastupdatedbyid, 
			string _lastupdatedbyname, System.DateTime _lastupdateddate, string _subject, 
			System.Boolean? _secondRequest)
		{
			BbQueryForCentre newBbQueryForCentre = new BbQueryForCentre();
			newBbQueryForCentre.Centreid = _centreid;
			newBbQueryForCentre.Messagecount = _messagecount;
			newBbQueryForCentre.Adminunread = _adminunread;
			newBbQueryForCentre.Clinicianunread = _clinicianunread;
			newBbQueryForCentre.QueryTypeId = _queryTypeId;
			newBbQueryForCentre.QueryStatusId = _queryStatusId;
			newBbQueryForCentre.Include = _include;
			newBbQueryForCentre.Createdbyid = _createdbyid;
			newBbQueryForCentre.Createdbyname = _createdbyname;
			newBbQueryForCentre.Createddate = _createddate;
			newBbQueryForCentre.Lastupdatedbyid = _lastupdatedbyid;
			newBbQueryForCentre.Lastupdatedbyname = _lastupdatedbyname;
			newBbQueryForCentre.Lastupdateddate = _lastupdateddate;
			newBbQueryForCentre.Subject = _subject;
			newBbQueryForCentre.SecondRequest = _secondRequest;
			return newBbQueryForCentre;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Qid property. 
		///		Unique ID for each row of this table
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@"Unique ID for each row of this table"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual int Qid
		{
			get
			{
				return this.entityData.Qid; 
			}
			
			set
			{
				if (this.entityData.Qid == value)
					return;
				
                OnPropertyChanging("Qid");                    
				OnColumnChanging(BbQueryForCentreColumn.Qid, this.entityData.Qid);
				this.entityData.Qid = value;
				this.EntityId.Qid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Qid, this.entityData.Qid);
				OnPropertyChanged("Qid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Centreid property. 
		///		Centre ID to separate queries by centre
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Centre ID to separate queries by centre"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Centreid
		{
			get
			{
				return this.entityData.Centreid; 
			}
			
			set
			{
				if (this.entityData.Centreid == value)
					return;
				
                OnPropertyChanging("Centreid");                    
				OnColumnChanging(BbQueryForCentreColumn.Centreid, this.entityData.Centreid);
				this.entityData.Centreid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Centreid, this.entityData.Centreid);
				OnPropertyChanged("Centreid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Messagecount property. 
		///		number of responses added to the query
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"number of responses added to the query"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Messagecount
		{
			get
			{
				return this.entityData.Messagecount; 
			}
			
			set
			{
				if (this.entityData.Messagecount == value)
					return;
				
                OnPropertyChanging("Messagecount");                    
				OnColumnChanging(BbQueryForCentreColumn.Messagecount, this.entityData.Messagecount);
				this.entityData.Messagecount = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Messagecount, this.entityData.Messagecount);
				OnPropertyChanged("Messagecount");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Adminunread property. 
		///		Has any admin read (opened) it?
		/// 		/// 0=Yes (Admin has read it)
		/// 		/// 1=No (Admin has not read it)
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Has any admin read (opened) it? 0=Yes (Admin has read it) 1=No (Admin has not read it)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual bool Adminunread
		{
			get
			{
				return this.entityData.Adminunread; 
			}
			
			set
			{
				if (this.entityData.Adminunread == value)
					return;
				
                OnPropertyChanging("Adminunread");                    
				OnColumnChanging(BbQueryForCentreColumn.Adminunread, this.entityData.Adminunread);
				this.entityData.Adminunread = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Adminunread, this.entityData.Adminunread);
				OnPropertyChanged("Adminunread");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Clinicianunread property. 
		///		Has any clinician (opened) it?
		/// 		/// 0=Yes (Clinician has opened it)
		/// 		/// 1=No (Clinician hasn't opened it)
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Has any clinician (opened) it? 0=Yes (Clinician has opened it) 1=No (Clinician hasn't opened it)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual bool Clinicianunread
		{
			get
			{
				return this.entityData.Clinicianunread; 
			}
			
			set
			{
				if (this.entityData.Clinicianunread == value)
					return;
				
                OnPropertyChanging("Clinicianunread");                    
				OnColumnChanging(BbQueryForCentreColumn.Clinicianunread, this.entityData.Clinicianunread);
				this.entityData.Clinicianunread = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Clinicianunread, this.entityData.Clinicianunread);
				OnPropertyChanged("Clinicianunread");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the QueryTypeId property. 
		///		Query Type ID (Foreign Key) Links to the table that contains all query types
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Query Type ID (Foreign Key) Links to the table that contains all query types"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int QueryTypeId
		{
			get
			{
				return this.entityData.QueryTypeId; 
			}
			
			set
			{
				if (this.entityData.QueryTypeId == value)
					return;
				
                OnPropertyChanging("QueryTypeId");                    
				OnColumnChanging(BbQueryForCentreColumn.QueryTypeId, this.entityData.QueryTypeId);
				this.entityData.QueryTypeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.QueryTypeId, this.entityData.QueryTypeId);
				OnPropertyChanged("QueryTypeId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the QueryStatusId property. 
		///		Query Status ID (Foreign Key) Links to the table that contain all query statuses
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Query Status ID (Foreign Key) Links to the table that contain all query statuses"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int QueryStatusId
		{
			get
			{
				return this.entityData.QueryStatusId; 
			}
			
			set
			{
				if (this.entityData.QueryStatusId == value)
					return;
				
                OnPropertyChanging("QueryStatusId");                    
				OnColumnChanging(BbQueryForCentreColumn.QueryStatusId, this.entityData.QueryStatusId);
				this.entityData.QueryStatusId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.QueryStatusId, this.entityData.QueryStatusId);
				OnPropertyChanged("QueryStatusId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Include property. 
		///		Is this a valid query?
		/// 		/// 0=No
		/// 		/// 1=Yes
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Is this a valid query? 0=No 1=Yes"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual bool Include
		{
			get
			{
				return this.entityData.Include; 
			}
			
			set
			{
				if (this.entityData.Include == value)
					return;
				
                OnPropertyChanging("Include");                    
				OnColumnChanging(BbQueryForCentreColumn.Include, this.entityData.Include);
				this.entityData.Include = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Include, this.entityData.Include);
				OnPropertyChanged("Include");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyid property. 
		///		Created by (id)
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Created by (id)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Createdbyid
		{
			get
			{
				return this.entityData.Createdbyid; 
			}
			
			set
			{
				if (this.entityData.Createdbyid == value)
					return;
				
                OnPropertyChanging("Createdbyid");                    
				OnColumnChanging(BbQueryForCentreColumn.Createdbyid, this.entityData.Createdbyid);
				this.entityData.Createdbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Createdbyid, this.entityData.Createdbyid);
				OnPropertyChanged("Createdbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createdbyname property. 
		///		Created by
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@"Created by"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual string Createdbyname
		{
			get
			{
				return this.entityData.Createdbyname; 
			}
			
			set
			{
				if (this.entityData.Createdbyname == value)
					return;
				
                OnPropertyChanging("Createdbyname");                    
				OnColumnChanging(BbQueryForCentreColumn.Createdbyname, this.entityData.Createdbyname);
				this.entityData.Createdbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Createdbyname, this.entityData.Createdbyname);
				OnPropertyChanged("Createdbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Createddate property. 
		///		Date created
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Date created"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Createddate
		{
			get
			{
				return this.entityData.Createddate; 
			}
			
			set
			{
				if (this.entityData.Createddate == value)
					return;
				
                OnPropertyChanging("Createddate");                    
				OnColumnChanging(BbQueryForCentreColumn.Createddate, this.entityData.Createddate);
				this.entityData.Createddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Createddate, this.entityData.Createddate);
				OnPropertyChanged("Createddate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyid property. 
		///		Last updated by (id) (including any responses)
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Last updated by (id) (including any responses)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual int Lastupdatedbyid
		{
			get
			{
				return this.entityData.Lastupdatedbyid; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyid == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyid");                    
				OnColumnChanging(BbQueryForCentreColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				this.entityData.Lastupdatedbyid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Lastupdatedbyid, this.entityData.Lastupdatedbyid);
				OnPropertyChanged("Lastupdatedbyid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdatedbyname property. 
		///		Last updated by (Including any responses)
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@"Last updated by (Including any responses)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual string Lastupdatedbyname
		{
			get
			{
				return this.entityData.Lastupdatedbyname; 
			}
			
			set
			{
				if (this.entityData.Lastupdatedbyname == value)
					return;
				
                OnPropertyChanging("Lastupdatedbyname");                    
				OnColumnChanging(BbQueryForCentreColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				this.entityData.Lastupdatedbyname = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Lastupdatedbyname, this.entityData.Lastupdatedbyname);
				OnPropertyChanged("Lastupdatedbyname");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Lastupdateddate property. 
		///		Date last updated (including any responses)
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Date last updated (including any responses)"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Lastupdateddate
		{
			get
			{
				return this.entityData.Lastupdateddate; 
			}
			
			set
			{
				if (this.entityData.Lastupdateddate == value)
					return;
				
                OnPropertyChanging("Lastupdateddate");                    
				OnColumnChanging(BbQueryForCentreColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				this.entityData.Lastupdateddate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Lastupdateddate, this.entityData.Lastupdateddate);
				OnPropertyChanged("Lastupdateddate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Subject property. 
		///		Query Text
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@"Query Text"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual string Subject
		{
			get
			{
				return this.entityData.Subject; 
			}
			
			set
			{
				if (this.entityData.Subject == value)
					return;
				
                OnPropertyChanging("Subject");                    
				OnColumnChanging(BbQueryForCentreColumn.Subject, this.entityData.Subject);
				this.entityData.Subject = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.Subject, this.entityData.Subject);
				OnPropertyChanged("Subject");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SecondRequest property. 
		///		Is this a high priority query?
		/// 		/// 0=No
		/// 		/// 1=Yes
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@"Is this a high priority query? 0=No 1=Yes"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? SecondRequest
		{
			get
			{
				return this.entityData.SecondRequest; 
			}
			
			set
			{
				if (this.entityData.SecondRequest == value)
					return;
				
                OnPropertyChanging("SecondRequest");                    
				OnColumnChanging(BbQueryForCentreColumn.SecondRequest, this.entityData.SecondRequest);
				this.entityData.SecondRequest = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BbQueryForCentreColumn.SecondRequest, this.entityData.SecondRequest);
				OnPropertyChanged("SecondRequest");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="BbCentre"/>.
		/// </summary>
		/// <value>The source BbCentre for Centreid.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual BbCentre CentreidSource
      	{
            get { return entityData.CentreidSource; }
            set { entityData.CentreidSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="BbQueryStatuslkp"/>.
		/// </summary>
		/// <value>The source BbQueryStatuslkp for QueryStatusId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual BbQueryStatuslkp QueryStatusIdSource
      	{
            get { return entityData.QueryStatusIdSource; }
            set { entityData.QueryStatusIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="BbQueryTypelkp"/>.
		/// </summary>
		/// <value>The source BbQueryTypelkp for QueryTypeId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual BbQueryTypelkp QueryTypeIdSource
      	{
            get { return entityData.QueryTypeIdSource; }
            set { entityData.QueryTypeIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of BbQueryForCentreMessage objects
		///	which are related to this object through the relation FK_bbQueryForCentreMessage_bbQueryForCentre
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<BbQueryForCentreMessage> BbQueryForCentreMessageCollection
		{
			get { return entityData.BbQueryForCentreMessageCollection; }
			set { entityData.BbQueryForCentreMessageCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Createdbyname", "Createdbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Createdbyname", "Createdbyname", 100));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Lastupdatedbyname", "Lastupdatedbyname"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Lastupdatedbyname", "Lastupdatedbyname", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "bbQueryForCentre"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"QId", "centreid", "messagecount", "adminunread", "clinicianunread", "QueryTypeId", "QueryStatusId", "include", "createdbyid", "createdbyname", "createddate", "lastupdatedbyid", "lastupdatedbyname", "lastupdateddate", "subject", "secondRequest"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as BbQueryForCentreEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (BbQueryForCentre) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<BbQueryForCentre>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as BbQueryForCentre);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed BbQueryForCentre Entity 
		///</summary>
		protected virtual BbQueryForCentre Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			BbQueryForCentre copy = new BbQueryForCentre();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Qid = this.Qid;
				copy.Centreid = this.Centreid;
				copy.Messagecount = this.Messagecount;
				copy.Adminunread = this.Adminunread;
				copy.Clinicianunread = this.Clinicianunread;
				copy.QueryTypeId = this.QueryTypeId;
				copy.QueryStatusId = this.QueryStatusId;
				copy.Include = this.Include;
				copy.Createdbyid = this.Createdbyid;
				copy.Createdbyname = this.Createdbyname;
				copy.Createddate = this.Createddate;
				copy.Lastupdatedbyid = this.Lastupdatedbyid;
				copy.Lastupdatedbyname = this.Lastupdatedbyname;
				copy.Lastupdateddate = this.Lastupdateddate;
				copy.Subject = this.Subject;
				copy.SecondRequest = this.SecondRequest;
			
			if (this.CentreidSource != null && existingCopies.Contains(this.CentreidSource))
				copy.CentreidSource = existingCopies[this.CentreidSource] as BbCentre;
			else
				copy.CentreidSource = MakeCopyOf(this.CentreidSource, existingCopies) as BbCentre;
			if (this.QueryStatusIdSource != null && existingCopies.Contains(this.QueryStatusIdSource))
				copy.QueryStatusIdSource = existingCopies[this.QueryStatusIdSource] as BbQueryStatuslkp;
			else
				copy.QueryStatusIdSource = MakeCopyOf(this.QueryStatusIdSource, existingCopies) as BbQueryStatuslkp;
			if (this.QueryTypeIdSource != null && existingCopies.Contains(this.QueryTypeIdSource))
				copy.QueryTypeIdSource = existingCopies[this.QueryTypeIdSource] as BbQueryTypelkp;
			else
				copy.QueryTypeIdSource = MakeCopyOf(this.QueryTypeIdSource, existingCopies) as BbQueryTypelkp;
		
			//deep copy nested objects
			copy.BbQueryForCentreMessageCollection = (TList<BbQueryForCentreMessage>) MakeCopyOf(this.BbQueryForCentreMessageCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed BbQueryForCentre Entity 
		///</summary>
		public virtual BbQueryForCentre Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed BbQueryForCentre Entity which is a deep copy of the current entity.
		///</summary>
		public virtual BbQueryForCentre DeepCopy()
		{
			return EntityHelper.Clone<BbQueryForCentre>(this as BbQueryForCentre);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as BbQueryForCentreEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new BbQueryForCentreEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as BbQueryForCentreEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(BbQueryForCentreColumn column)
		{
			switch(column)
			{
					case BbQueryForCentreColumn.Qid:
					return entityData.Qid != _originalData.Qid;
					case BbQueryForCentreColumn.Centreid:
					return entityData.Centreid != _originalData.Centreid;
					case BbQueryForCentreColumn.Messagecount:
					return entityData.Messagecount != _originalData.Messagecount;
					case BbQueryForCentreColumn.Adminunread:
					return entityData.Adminunread != _originalData.Adminunread;
					case BbQueryForCentreColumn.Clinicianunread:
					return entityData.Clinicianunread != _originalData.Clinicianunread;
					case BbQueryForCentreColumn.QueryTypeId:
					return entityData.QueryTypeId != _originalData.QueryTypeId;
					case BbQueryForCentreColumn.QueryStatusId:
					return entityData.QueryStatusId != _originalData.QueryStatusId;
					case BbQueryForCentreColumn.Include:
					return entityData.Include != _originalData.Include;
					case BbQueryForCentreColumn.Createdbyid:
					return entityData.Createdbyid != _originalData.Createdbyid;
					case BbQueryForCentreColumn.Createdbyname:
					return entityData.Createdbyname != _originalData.Createdbyname;
					case BbQueryForCentreColumn.Createddate:
					return entityData.Createddate != _originalData.Createddate;
					case BbQueryForCentreColumn.Lastupdatedbyid:
					return entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
					case BbQueryForCentreColumn.Lastupdatedbyname:
					return entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
					case BbQueryForCentreColumn.Lastupdateddate:
					return entityData.Lastupdateddate != _originalData.Lastupdateddate;
					case BbQueryForCentreColumn.Subject:
					return entityData.Subject != _originalData.Subject;
					case BbQueryForCentreColumn.SecondRequest:
					return entityData.SecondRequest != _originalData.SecondRequest;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< BbQueryForCentreColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Qid != _originalData.Qid;
			result = result || entityData.Centreid != _originalData.Centreid;
			result = result || entityData.Messagecount != _originalData.Messagecount;
			result = result || entityData.Adminunread != _originalData.Adminunread;
			result = result || entityData.Clinicianunread != _originalData.Clinicianunread;
			result = result || entityData.QueryTypeId != _originalData.QueryTypeId;
			result = result || entityData.QueryStatusId != _originalData.QueryStatusId;
			result = result || entityData.Include != _originalData.Include;
			result = result || entityData.Createdbyid != _originalData.Createdbyid;
			result = result || entityData.Createdbyname != _originalData.Createdbyname;
			result = result || entityData.Createddate != _originalData.Createddate;
			result = result || entityData.Lastupdatedbyid != _originalData.Lastupdatedbyid;
			result = result || entityData.Lastupdatedbyname != _originalData.Lastupdatedbyname;
			result = result || entityData.Lastupdateddate != _originalData.Lastupdateddate;
			result = result || entityData.Subject != _originalData.Subject;
			result = result || entityData.SecondRequest != _originalData.SecondRequest;
			return result;
		}	
		
		///<summary>
		///  Returns a BbQueryForCentre Entity with the original data.
		///</summary>
		public BbQueryForCentre GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateBbQueryForCentre(
				_originalData.Centreid,
				_originalData.Messagecount,
				_originalData.Adminunread,
				_originalData.Clinicianunread,
				_originalData.QueryTypeId,
				_originalData.QueryStatusId,
				_originalData.Include,
				_originalData.Createdbyid,
				_originalData.Createdbyname,
				_originalData.Createddate,
				_originalData.Lastupdatedbyid,
				_originalData.Lastupdatedbyname,
				_originalData.Lastupdateddate,
				_originalData.Subject,
				_originalData.SecondRequest
				);
				
			return (BbQueryForCentre)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="BbQueryForCentreBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is BbQueryForCentreBase)
				return ValueEquals(this, (BbQueryForCentreBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="BbQueryForCentreBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Qid.GetHashCode() ^ 
					this.Centreid.GetHashCode() ^ 
					this.Messagecount.GetHashCode() ^ 
					this.Adminunread.GetHashCode() ^ 
					this.Clinicianunread.GetHashCode() ^ 
					this.QueryTypeId.GetHashCode() ^ 
					this.QueryStatusId.GetHashCode() ^ 
					this.Include.GetHashCode() ^ 
					this.Createdbyid.GetHashCode() ^ 
					this.Createdbyname.GetHashCode() ^ 
					this.Createddate.GetHashCode() ^ 
					this.Lastupdatedbyid.GetHashCode() ^ 
					this.Lastupdatedbyname.GetHashCode() ^ 
					this.Lastupdateddate.GetHashCode() ^ 
					((this.Subject == null) ? string.Empty : this.Subject.ToString()).GetHashCode() ^ 
					((this.SecondRequest == null) ? string.Empty : this.SecondRequest.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="BbQueryForCentreBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(BbQueryForCentreBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="BbQueryForCentreBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="BbQueryForCentreBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="BbQueryForCentreBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(BbQueryForCentreBase Object1, BbQueryForCentreBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Qid != Object2.Qid)
				equal = false;
			if (Object1.Centreid != Object2.Centreid)
				equal = false;
			if (Object1.Messagecount != Object2.Messagecount)
				equal = false;
			if (Object1.Adminunread != Object2.Adminunread)
				equal = false;
			if (Object1.Clinicianunread != Object2.Clinicianunread)
				equal = false;
			if (Object1.QueryTypeId != Object2.QueryTypeId)
				equal = false;
			if (Object1.QueryStatusId != Object2.QueryStatusId)
				equal = false;
			if (Object1.Include != Object2.Include)
				equal = false;
			if (Object1.Createdbyid != Object2.Createdbyid)
				equal = false;
			if (Object1.Createdbyname != Object2.Createdbyname)
				equal = false;
			if (Object1.Createddate != Object2.Createddate)
				equal = false;
			if (Object1.Lastupdatedbyid != Object2.Lastupdatedbyid)
				equal = false;
			if (Object1.Lastupdatedbyname != Object2.Lastupdatedbyname)
				equal = false;
			if (Object1.Lastupdateddate != Object2.Lastupdateddate)
				equal = false;
			if ( Object1.Subject != null && Object2.Subject != null )
			{
				if (Object1.Subject != Object2.Subject)
					equal = false;
			}
			else if (Object1.Subject == null ^ Object2.Subject == null )
			{
				equal = false;
			}
			if ( Object1.SecondRequest != null && Object2.SecondRequest != null )
			{
				if (Object1.SecondRequest != Object2.SecondRequest)
					equal = false;
			}
			else if (Object1.SecondRequest == null ^ Object2.SecondRequest == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((BbQueryForCentreBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static BbQueryForCentreComparer GetComparer()
        {
            return new BbQueryForCentreComparer();
        }
        */

        // Comparer delegates back to BbQueryForCentre
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(BbQueryForCentre rhs, BbQueryForCentreColumn which)
        {
            switch (which)
            {
            	
            	
            	case BbQueryForCentreColumn.Qid:
            		return this.Qid.CompareTo(rhs.Qid);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Centreid:
            		return this.Centreid.CompareTo(rhs.Centreid);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Messagecount:
            		return this.Messagecount.CompareTo(rhs.Messagecount);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Adminunread:
            		return this.Adminunread.CompareTo(rhs.Adminunread);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Clinicianunread:
            		return this.Clinicianunread.CompareTo(rhs.Clinicianunread);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.QueryTypeId:
            		return this.QueryTypeId.CompareTo(rhs.QueryTypeId);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.QueryStatusId:
            		return this.QueryStatusId.CompareTo(rhs.QueryStatusId);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Include:
            		return this.Include.CompareTo(rhs.Include);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Createdbyid:
            		return this.Createdbyid.CompareTo(rhs.Createdbyid);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Createdbyname:
            		return this.Createdbyname.CompareTo(rhs.Createdbyname);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Createddate:
            		return this.Createddate.CompareTo(rhs.Createddate);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Lastupdatedbyid:
            		return this.Lastupdatedbyid.CompareTo(rhs.Lastupdatedbyid);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Lastupdatedbyname:
            		return this.Lastupdatedbyname.CompareTo(rhs.Lastupdatedbyname);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Lastupdateddate:
            		return this.Lastupdateddate.CompareTo(rhs.Lastupdateddate);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.Subject:
            		return this.Subject.CompareTo(rhs.Subject);
            		
            		                 
            	
            	
            	case BbQueryForCentreColumn.SecondRequest:
            		return this.SecondRequest.Value.CompareTo(rhs.SecondRequest.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<BbQueryForCentreKey> Members
		
		// member variable for the EntityId property
		private BbQueryForCentreKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual BbQueryForCentreKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new BbQueryForCentreKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("BbQueryForCentre")
					.Append("|").Append( this.Qid.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{17}{16}- Qid: {0}{16}- Centreid: {1}{16}- Messagecount: {2}{16}- Adminunread: {3}{16}- Clinicianunread: {4}{16}- QueryTypeId: {5}{16}- QueryStatusId: {6}{16}- Include: {7}{16}- Createdbyid: {8}{16}- Createdbyname: {9}{16}- Createddate: {10}{16}- Lastupdatedbyid: {11}{16}- Lastupdatedbyname: {12}{16}- Lastupdateddate: {13}{16}- Subject: {14}{16}- SecondRequest: {15}{16}{18}", 
				this.Qid,
				this.Centreid,
				this.Messagecount,
				this.Adminunread,
				this.Clinicianunread,
				this.QueryTypeId,
				this.QueryStatusId,
				this.Include,
				this.Createdbyid,
				this.Createdbyname,
				this.Createddate,
				this.Lastupdatedbyid,
				this.Lastupdatedbyname,
				this.Lastupdateddate,
				(this.Subject == null) ? string.Empty : this.Subject.ToString(),
				(this.SecondRequest == null) ? string.Empty : this.SecondRequest.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'bbQueryForCentre' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class BbQueryForCentreEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// QId : Unique ID for each row of this table
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "bbQueryForCentre"</remarks>
		public int Qid;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// centreid : Centre ID to separate queries by centre
		/// </summary>
		public int Centreid = (int)0;
		
		/// <summary>
		/// messagecount : number of responses added to the query
		/// </summary>
		public int Messagecount = (int)0;
		
		/// <summary>
		/// adminunread : Has any admin read (opened) it?
		/// 		/// 0=Yes (Admin has read it)
		/// 		/// 1=No (Admin has not read it)
		/// </summary>
		public bool Adminunread = false;
		
		/// <summary>
		/// clinicianunread : Has any clinician (opened) it?
		/// 		/// 0=Yes (Clinician has opened it)
		/// 		/// 1=No (Clinician hasn't opened it)
		/// </summary>
		public bool Clinicianunread = false;
		
		/// <summary>
		/// QueryTypeId : Query Type ID (Foreign Key) Links to the table that contains all query types
		/// </summary>
		public int QueryTypeId = (int)0;
		
		/// <summary>
		/// QueryStatusId : Query Status ID (Foreign Key) Links to the table that contain all query statuses
		/// </summary>
		public int QueryStatusId = (int)0;
		
		/// <summary>
		/// include : Is this a valid query?
		/// 		/// 0=No
		/// 		/// 1=Yes
		/// </summary>
		public bool Include = false;
		
		/// <summary>
		/// createdbyid : Created by (id)
		/// </summary>
		public int Createdbyid = (int)0;
		
		/// <summary>
		/// createdbyname : Created by
		/// </summary>
		public string Createdbyname = string.Empty;
		
		/// <summary>
		/// createddate : Date created
		/// </summary>
		public System.DateTime Createddate = DateTime.Now;
		
		/// <summary>
		/// lastupdatedbyid : Last updated by (id) (including any responses)
		/// </summary>
		public int Lastupdatedbyid = (int)0;
		
		/// <summary>
		/// lastupdatedbyname : Last updated by (Including any responses)
		/// </summary>
		public string Lastupdatedbyname = string.Empty;
		
		/// <summary>
		/// lastupdateddate : Date last updated (including any responses)
		/// </summary>
		public System.DateTime Lastupdateddate = DateTime.Now;
		
		/// <summary>
		/// subject : Query Text
		/// </summary>
		public string Subject = null;
		
		/// <summary>
		/// secondRequest : Is this a high priority query?
		/// 		/// 0=No
		/// 		/// 1=Yes
		/// </summary>
		public System.Boolean? SecondRequest = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private BbCentre _centreidSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="BbCentre"/>.
		/// </summary>
		/// <value>The source BbCentre for Centreid.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual BbCentre CentreidSource
      	{
            get { return this._centreidSource; }
            set { this._centreidSource = value; }
      	}
		private BbQueryStatuslkp _queryStatusIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="BbQueryStatuslkp"/>.
		/// </summary>
		/// <value>The source BbQueryStatuslkp for QueryStatusId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual BbQueryStatuslkp QueryStatusIdSource
      	{
            get { return this._queryStatusIdSource; }
            set { this._queryStatusIdSource = value; }
      	}
		private BbQueryTypelkp _queryTypeIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="BbQueryTypelkp"/>.
		/// </summary>
		/// <value>The source BbQueryTypelkp for QueryTypeId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual BbQueryTypelkp QueryTypeIdSource
      	{
            get { return this._queryTypeIdSource; }
            set { this._queryTypeIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region BbQueryForCentreMessageCollection
		
		private TList<BbQueryForCentreMessage> _bbQueryForCentreMessageQid;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _bbQueryForCentreMessageQid
		/// </summary>
		
		public TList<BbQueryForCentreMessage> BbQueryForCentreMessageCollection
		{
			get
			{
				if (_bbQueryForCentreMessageQid == null)
				{
				_bbQueryForCentreMessageQid = new TList<BbQueryForCentreMessage>();
				}
	
				return _bbQueryForCentreMessageQid;
			}
			set { _bbQueryForCentreMessageQid = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			BbQueryForCentreEntityData _tmp = new BbQueryForCentreEntityData();
						
			_tmp.Qid = this.Qid;
			
			_tmp.Centreid = this.Centreid;
			_tmp.Messagecount = this.Messagecount;
			_tmp.Adminunread = this.Adminunread;
			_tmp.Clinicianunread = this.Clinicianunread;
			_tmp.QueryTypeId = this.QueryTypeId;
			_tmp.QueryStatusId = this.QueryStatusId;
			_tmp.Include = this.Include;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			_tmp.Subject = this.Subject;
			_tmp.SecondRequest = this.SecondRequest;
			
			#region Source Parent Composite Entities
			if (this.CentreidSource != null)
				_tmp.CentreidSource = MakeCopyOf(this.CentreidSource) as BbCentre;
			if (this.QueryStatusIdSource != null)
				_tmp.QueryStatusIdSource = MakeCopyOf(this.QueryStatusIdSource) as BbQueryStatuslkp;
			if (this.QueryTypeIdSource != null)
				_tmp.QueryTypeIdSource = MakeCopyOf(this.QueryTypeIdSource) as BbQueryTypelkp;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._bbQueryForCentreMessageQid != null)
				_tmp.BbQueryForCentreMessageCollection = (TList<BbQueryForCentreMessage>) MakeCopyOf(this.BbQueryForCentreMessageCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			BbQueryForCentreEntityData _tmp = new BbQueryForCentreEntityData();
						
			_tmp.Qid = this.Qid;
			
			_tmp.Centreid = this.Centreid;
			_tmp.Messagecount = this.Messagecount;
			_tmp.Adminunread = this.Adminunread;
			_tmp.Clinicianunread = this.Clinicianunread;
			_tmp.QueryTypeId = this.QueryTypeId;
			_tmp.QueryStatusId = this.QueryStatusId;
			_tmp.Include = this.Include;
			_tmp.Createdbyid = this.Createdbyid;
			_tmp.Createdbyname = this.Createdbyname;
			_tmp.Createddate = this.Createddate;
			_tmp.Lastupdatedbyid = this.Lastupdatedbyid;
			_tmp.Lastupdatedbyname = this.Lastupdatedbyname;
			_tmp.Lastupdateddate = this.Lastupdateddate;
			_tmp.Subject = this.Subject;
			_tmp.SecondRequest = this.SecondRequest;
			
			#region Source Parent Composite Entities
			if (this.CentreidSource != null && existingCopies.Contains(this.CentreidSource))
				_tmp.CentreidSource = existingCopies[this.CentreidSource] as BbCentre;
			else
				_tmp.CentreidSource = MakeCopyOf(this.CentreidSource, existingCopies) as BbCentre;
			if (this.QueryStatusIdSource != null && existingCopies.Contains(this.QueryStatusIdSource))
				_tmp.QueryStatusIdSource = existingCopies[this.QueryStatusIdSource] as BbQueryStatuslkp;
			else
				_tmp.QueryStatusIdSource = MakeCopyOf(this.QueryStatusIdSource, existingCopies) as BbQueryStatuslkp;
			if (this.QueryTypeIdSource != null && existingCopies.Contains(this.QueryTypeIdSource))
				_tmp.QueryTypeIdSource = existingCopies[this.QueryTypeIdSource] as BbQueryTypelkp;
			else
				_tmp.QueryTypeIdSource = MakeCopyOf(this.QueryTypeIdSource, existingCopies) as BbQueryTypelkp;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.BbQueryForCentreMessageCollection = (TList<BbQueryForCentreMessage>) MakeCopyOf(this.BbQueryForCentreMessageCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbQueryForCentreColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(BbQueryForCentreColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbQueryForCentreColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(BbQueryForCentreColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbQueryForCentreColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(BbQueryForCentreColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				BbQueryForCentreEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new BbQueryForCentreEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BbQueryForCentreColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(BbQueryForCentreColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				BbQueryForCentreEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new BbQueryForCentreEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region BbQueryForCentreEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="BbQueryForCentre"/> object.
	/// </remarks>
	public class BbQueryForCentreEventArgs : System.EventArgs
	{
		private BbQueryForCentreColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the BbQueryForCentreEventArgs class.
		///</summary>
		public BbQueryForCentreEventArgs(BbQueryForCentreColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the BbQueryForCentreEventArgs class.
		///</summary>
		public BbQueryForCentreEventArgs(BbQueryForCentreColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The BbQueryForCentreColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="BbQueryForCentreColumn" />
		public BbQueryForCentreColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all BbQueryForCentre related events.
	///</summary>
	public delegate void BbQueryForCentreEventHandler(object sender, BbQueryForCentreEventArgs e);
	
	#region BbQueryForCentreComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class BbQueryForCentreComparer : System.Collections.Generic.IComparer<BbQueryForCentre>
	{
		BbQueryForCentreColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:BbQueryForCentreComparer"/> class.
        /// </summary>
		public BbQueryForCentreComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:BbQueryForCentreComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public BbQueryForCentreComparer(BbQueryForCentreColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="BbQueryForCentre"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="BbQueryForCentre"/> to compare.</param>
        /// <param name="b">The second <c>BbQueryForCentre</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(BbQueryForCentre a, BbQueryForCentre b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(BbQueryForCentre entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(BbQueryForCentre a, BbQueryForCentre b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public BbQueryForCentreColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region BbQueryForCentreKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="BbQueryForCentre"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class BbQueryForCentreKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the BbQueryForCentreKey class.
		/// </summary>
		public BbQueryForCentreKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the BbQueryForCentreKey class.
		/// </summary>
		public BbQueryForCentreKey(BbQueryForCentreBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Qid = entity.Qid;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the BbQueryForCentreKey class.
		/// </summary>
		public BbQueryForCentreKey(int _qid)
		{
			#region Init Properties

			this.Qid = _qid;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private BbQueryForCentreBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public BbQueryForCentreBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Qid property
		private int _qid;
		
		/// <summary>
		/// Gets or sets the Qid property.
		/// </summary>
		public int Qid
		{
			get { return _qid; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Qid = value;
				
				_qid = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Qid = ( values["Qid"] != null ) ? (int) EntityUtil.ChangeType(values["Qid"], typeof(int)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Qid", Qid);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Qid: {0}{1}",
								Qid,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region BbQueryForCentreColumn Enum
	
	/// <summary>
	/// Enumerate the BbQueryForCentre columns.
	/// </summary>
	[Serializable]
	public enum BbQueryForCentreColumn : int
	{
		/// <summary>
		/// Qid : Unique ID for each row of this table
		/// </summary>
		[EnumTextValue("Qid")]
		[ColumnEnum("QId", typeof(int), System.Data.DbType.Int32, true, true, false)]
		Qid = 1,
		/// <summary>
		/// Centreid : Centre ID to separate queries by centre
		/// </summary>
		[EnumTextValue("Centreid")]
		[ColumnEnum("centreid", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Centreid = 2,
		/// <summary>
		/// Messagecount : number of responses added to the query
		/// </summary>
		[EnumTextValue("Messagecount")]
		[ColumnEnum("messagecount", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Messagecount = 3,
		/// <summary>
		/// Adminunread : Has any admin read (opened) it?
		/// 		/// 0=Yes (Admin has read it)
		/// 		/// 1=No (Admin has not read it)
		/// </summary>
		[EnumTextValue("Adminunread")]
		[ColumnEnum("adminunread", typeof(bool), System.Data.DbType.Boolean, false, false, false)]
		Adminunread = 4,
		/// <summary>
		/// Clinicianunread : Has any clinician (opened) it?
		/// 		/// 0=Yes (Clinician has opened it)
		/// 		/// 1=No (Clinician hasn't opened it)
		/// </summary>
		[EnumTextValue("Clinicianunread")]
		[ColumnEnum("clinicianunread", typeof(bool), System.Data.DbType.Boolean, false, false, false)]
		Clinicianunread = 5,
		/// <summary>
		/// QueryTypeId : Query Type ID (Foreign Key) Links to the table that contains all query types
		/// </summary>
		[EnumTextValue("Query Type Id")]
		[ColumnEnum("QueryTypeId", typeof(int), System.Data.DbType.Int32, false, false, false)]
		QueryTypeId = 6,
		/// <summary>
		/// QueryStatusId : Query Status ID (Foreign Key) Links to the table that contain all query statuses
		/// </summary>
		[EnumTextValue("Query Status Id")]
		[ColumnEnum("QueryStatusId", typeof(int), System.Data.DbType.Int32, false, false, false)]
		QueryStatusId = 7,
		/// <summary>
		/// Include : Is this a valid query?
		/// 		/// 0=No
		/// 		/// 1=Yes
		/// </summary>
		[EnumTextValue("Include")]
		[ColumnEnum("include", typeof(bool), System.Data.DbType.Boolean, false, false, false)]
		Include = 8,
		/// <summary>
		/// Createdbyid : Created by (id)
		/// </summary>
		[EnumTextValue("Createdbyid")]
		[ColumnEnum("createdbyid", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Createdbyid = 9,
		/// <summary>
		/// Createdbyname : Created by
		/// </summary>
		[EnumTextValue("Createdbyname")]
		[ColumnEnum("createdbyname", typeof(string), System.Data.DbType.AnsiString, false, false, false, 100)]
		Createdbyname = 10,
		/// <summary>
		/// Createddate : Date created
		/// </summary>
		[EnumTextValue("Createddate")]
		[ColumnEnum("createddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Createddate = 11,
		/// <summary>
		/// Lastupdatedbyid : Last updated by (id) (including any responses)
		/// </summary>
		[EnumTextValue("Lastupdatedbyid")]
		[ColumnEnum("lastupdatedbyid", typeof(int), System.Data.DbType.Int32, false, false, false)]
		Lastupdatedbyid = 12,
		/// <summary>
		/// Lastupdatedbyname : Last updated by (Including any responses)
		/// </summary>
		[EnumTextValue("Lastupdatedbyname")]
		[ColumnEnum("lastupdatedbyname", typeof(string), System.Data.DbType.AnsiString, false, false, false, 100)]
		Lastupdatedbyname = 13,
		/// <summary>
		/// Lastupdateddate : Date last updated (including any responses)
		/// </summary>
		[EnumTextValue("Lastupdateddate")]
		[ColumnEnum("lastupdateddate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Lastupdateddate = 14,
		/// <summary>
		/// Subject : Query Text
		/// </summary>
		[EnumTextValue("Subject")]
		[ColumnEnum("subject", typeof(string), System.Data.DbType.AnsiString, false, false, true)]
		Subject = 15,
		/// <summary>
		/// SecondRequest : Is this a high priority query?
		/// 		/// 0=No
		/// 		/// 1=Yes
		/// </summary>
		[EnumTextValue("Second Request")]
		[ColumnEnum("secondRequest", typeof(System.Boolean?), System.Data.DbType.Boolean, false, false, true)]
		SecondRequest = 16
	}//End enum

	#endregion BbQueryForCentreColumn Enum

} // end namespace
