using System;
using System.ComponentModel;

namespace MHS.Badbir.NetTiers.Entities
{
	/// <summary>
	///		The data structure representation of the 'bbAdditionalUserAndCentre' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IBbAdditionalUserAndCentre 
	{
		/// <summary>			
		/// userid : User Id
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "bbAdditionalUserAndCentre"</remarks>
		System.Guid Userid { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Guid OriginalUserid { get; set; }
			
		/// <summary>			
		/// Centreid : Centre
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "bbAdditionalUserAndCentre"</remarks>
		int Centreid { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		int OriginalCentreid { get; set; }
			
		
		
		/// <summary>
		/// createdbyid : Created by (id)
		/// </summary>
		int  Createdbyid  { get; set; }
		
		/// <summary>
		/// createdbyname : Created by
		/// </summary>
		string  Createdbyname  { get; set; }
		
		/// <summary>
		/// createddate : Date created
		/// </summary>
		System.DateTime  Createddate  { get; set; }
		
		/// <summary>
		/// lastupdatedbyid : Last updated by (id)
		/// </summary>
		int  Lastupdatedbyid  { get; set; }
		
		/// <summary>
		/// lastupdatedbyname : Last updated by
		/// </summary>
		string  Lastupdatedbyname  { get; set; }
		
		/// <summary>
		/// lastupdateddate : Date last updated
		/// </summary>
		System.DateTime  Lastupdateddate  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


