using System;
using System.ComponentModel;

namespace MHS.Badbir.NetTiers.Entities
{
	/// <summary>
	///		The data structure representation of the 'bbQueryForCentre' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IBbQueryForCentre 
	{
		/// <summary>			
		/// QId : Unique ID for each row of this table
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "bbQueryForCentre"</remarks>
		int Qid { get; set; }
				
		
		
		/// <summary>
		/// centreid : Centre ID to separate queries by centre
		/// </summary>
		int  Centreid  { get; set; }
		
		/// <summary>
		/// messagecount : number of responses added to the query
		/// </summary>
		int  Messagecount  { get; set; }
		
		/// <summary>
		/// adminunread : Has any admin read (opened) it?
		/// 		/// 0=Yes (Admin has read it)
		/// 		/// 1=No (Admin has not read it)
		/// </summary>
		bool  Adminunread  { get; set; }
		
		/// <summary>
		/// clinicianunread : Has any clinician (opened) it?
		/// 		/// 0=Yes (Clinician has opened it)
		/// 		/// 1=No (Clinician hasn't opened it)
		/// </summary>
		bool  Clinicianunread  { get; set; }
		
		/// <summary>
		/// QueryTypeId : Query Type ID (Foreign Key) Links to the table that contains all query types
		/// </summary>
		int  QueryTypeId  { get; set; }
		
		/// <summary>
		/// QueryStatusId : Query Status ID (Foreign Key) Links to the table that contain all query statuses
		/// </summary>
		int  QueryStatusId  { get; set; }
		
		/// <summary>
		/// include : Is this a valid query?
		/// 		/// 0=No
		/// 		/// 1=Yes
		/// </summary>
		bool  Include  { get; set; }
		
		/// <summary>
		/// createdbyid : Created by (id)
		/// </summary>
		int  Createdbyid  { get; set; }
		
		/// <summary>
		/// createdbyname : Created by
		/// </summary>
		string  Createdbyname  { get; set; }
		
		/// <summary>
		/// createddate : Date created
		/// </summary>
		System.DateTime  Createddate  { get; set; }
		
		/// <summary>
		/// lastupdatedbyid : Last updated by (id) (including any responses)
		/// </summary>
		int  Lastupdatedbyid  { get; set; }
		
		/// <summary>
		/// lastupdatedbyname : Last updated by (Including any responses)
		/// </summary>
		string  Lastupdatedbyname  { get; set; }
		
		/// <summary>
		/// lastupdateddate : Date last updated (including any responses)
		/// </summary>
		System.DateTime  Lastupdateddate  { get; set; }
		
		/// <summary>
		/// subject : Query Text
		/// </summary>
		string  Subject  { get; set; }
		
		/// <summary>
		/// secondRequest : Is this a high priority query?
		/// 		/// 0=No
		/// 		/// 1=Yes
		/// </summary>
		System.Boolean?  SecondRequest  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _bbQueryForCentreMessageQid
		/// </summary>	
		TList<BbQueryForCentreMessage> BbQueryForCentreMessageCollection {  get;  set;}	

		#endregion Data Properties

	}
}


